/*
 * config_gz.c — /proc/config.gz — kernel build configuration export
 *
 * Embeds a gzip-compressed kernel build configuration generated at
 * build time, and serves it via the /proc/config.gz virtual file.
 * This allows userspace (including zcat) to inspect kernel build
 * options at runtime.
 *
 * The compressed data is generated by scripts/gen_config.sh and
 * embedded via build_config_gz.h, which is auto-generated from
 * the host-compressed config.gz file using xxd -i.
 */

#define KERNEL_INTERNAL
#include "types.h"
#include "printf.h"
#include "string.h"

/* ── Embedded compressed configuration data ────────────────────────────
 * Generated at build time by scripts/gen_config.sh and compressed
 * with gzip.  The variables below are defined by the auto-generated
 * header which is produced by xxd -i -n build_config_gz.
 */
#include "build_config_gz.h"

/* xxd -i -n build_config_gz produces:
 *   unsigned char build_config_gz[] = { ... };
 *   unsigned int build_config_gz_len = ...;
 */
extern unsigned char build_config_gz[];
extern unsigned int build_config_gz_len;

/* ── Public API ──────────────────────────────────────────────────────── */

/**
 * config_gz_get_data - Return a pointer to the compressed kernel config
 * @out_size: On success, set to the size of the compressed data in bytes
 *
 * Provides access to the embedded gzip-compressed kernel build
 * configuration.  The data is generated at build time by
 * scripts/gen_config.sh and embedded via build_config_gz.h.
 *
 * Return: A pointer to the compressed config data, or NULL if @out_size
 *         is NULL or the embedded data is empty
 */
const void *config_gz_get_data(uint32_t *out_size)
{
    if (!out_size)
        return NULL;
    *out_size = (uint32_t)build_config_gz_len;
    return (const void *)build_config_gz;
}

/**
 * config_gz_get_uncompressed - Return the uncompressed config text
 * @buf: Destination buffer for the uncompressed config
 * @max_len: Maximum number of bytes to write to @buf
 *
 * This operation is not directly supported — userspace should use
 * zcat /proc/config.gz to decompress the embedded data.
 *
 * Return: -ENOSYS, as this function is not yet implemented
 */
int config_gz_get_uncompressed(char *buf, int max_len)
{
    (void)buf;
    (void)max_len;
    return -ENOSYS;
}

/* ── Initialization ─────────────────────────────────────────────────── */

/**
 * config_gz_init - Initialise the /proc/config.gz subsystem
 *
 * Prints a boot message indicating whether the embedded compressed
 * configuration data is available and its size.  Called once during
 * kernel initialisation.
 */
void config_gz_init(void)
{
    uint32_t size = 0;
    const void *data = config_gz_get_data(&size);
    if (data && size > 0) {
        kprintf("[OK] config_gz: /proc/config.gz available (%u bytes compressed)\\n",
                (unsigned int)size);
    } else {
        kprintf("[!!] config_gz: no embedded config data\\n");
    }
}

/* ── Stub: config_gz_decompress ─────────────────────────────── */
static int config_gz_decompress(const void *src, size_t slen, void *dst, size_t *dlen)
{
    (void)src;
    (void)slen;
    (void)dst;
    (void)dlen;
    kprintf("[config] config_gz_decompress: not yet implemented\n");
    return 0;
}
/* ── Stub: config_gz_compress ─────────────────────────────── */
static int config_gz_compress(const void *src, size_t slen, void *dst, size_t *dlen)
{
    (void)src;
    (void)slen;
    (void)dst;
    (void)dlen;
    kprintf("[config] config_gz_compress: not yet implemented\n");
    return 0;
}
