#define KERNEL_INTERNAL
#include "kpti.h"
#include "vmm.h"
#include "pmm.h"
#include "printf.h"
#include "string.h"
#include "cpu.h"
#include "smp.h"
#include "process.h"
#include "cpu_features.h"

/* ── Embedded trampoline binary ────────────────────────────────────
 * Generated by: nasm -f bin → xxd -i → kpti_trampoline_bin.h
 * Contains the flat binary with org KPTI_TRAMPOLINE_VADDR.
 */
#include "kpti_trampoline_bin.h"
/* Provides:
 *   unsigned char kpti_trampoline_bin[];
 *   unsigned int kpti_trampoline_bin_len;
 */

/* ── Trampoline page per-CPU data accessors ───────────────────────
 * The trampoline page is at KPTI_TRAMPOLINE_VADDR, mapped in both
 * kernel and user page tables.  Data at fixed offsets is accessed
 * via direct virtual address reads/writes. */
#define tramp_read(offs)    (*(volatile uint64_t *)(KPTI_TRAMPOLINE_VADDR + (offs)))
#define tramp_write(offs, v) (*(volatile uint64_t *)(KPTI_TRAMPOLINE_VADDR + (offs)) = (v))

/* ── Page table entry constants (from x86-64 spec) ─────────────── */
/* Note: these match the raw x86-64 PTE bits. VMM_FLAG_* in vmm.h
 * uses the same bit positions but different names.  We define our own
 * here to avoid depending on private defines in vmm.c. */
#define KPTI_PTE_PRESENT   (1ULL << 0)
#define KPTI_PTE_WRITE     (1ULL << 1)
#define KPTI_PTE_USER      (1ULL << 2)
#define KPTI_PTE_GLOBAL    (1ULL << 8)
#define KPTI_PTE_NX        (1ULL << 63)
#define KPTI_PTE_ADDR_MASK 0x000FFFFFFFFFF000ULL
#define KPTI_PAGE_SIZE     0x1000ULL

/* ── Static state ──────────────────────────────────────────────── */
static int kpti_active = 0;
static uint64_t trampoline_phys = 0;  /* physical frame of trampoline page */

/* ── Initialize KPTI ────────────────────────────────────────────────
 * Called once during boot, after VMM, SMAP/SMEP, and INVPCID init. */
void kpti_init(void) {
    if (kpti_active) return;

    if (!kpti_trampoline_bin_len || kpti_trampoline_bin_len > 0x1000) {
        kprintf("[KPTI] No valid trampoline binary (%u bytes) — KPTI disabled\n",
                kpti_trampoline_bin_len);
        return;
    }

    kprintf("[KPTI] Initializing Kernel Page-Table Isolation...\n");

    /* 1. Allocate a physical frame for the trampoline */
    trampoline_phys = pmm_alloc_frame();
    if (!trampoline_phys) {
        kprintf("[KPTI] FAIL: out of memory for trampoline\n");
        return;
    }
    uint64_t *tramp_virt = (uint64_t *)PHYS_TO_VIRT(trampoline_phys);
    memset(tramp_virt, 0, KPTI_PAGE_SIZE);

    /* 2. Copy the trampoline binary into the frame */
    memcpy(tramp_virt, kpti_trampoline_bin,
           kpti_trampoline_bin_len < 0x1000 ? kpti_trampoline_bin_len : 0x1000);

    /* 3. Map trampoline at KPTI_TRAMPOLINE_VADDR in kernel page table.
     *    Supervisor-only (no USER bit), both read-write and nx enforced via
     *    the standard page-table helpers. */
    uint64_t *kernel_pml4 = vmm_get_pml4();
    int ret = vmm_map_page(KPTI_TRAMPOLINE_VADDR, trampoline_phys,
                           KPTI_PTE_PRESENT | KPTI_PTE_WRITE | KPTI_PTE_GLOBAL);
    if (ret < 0) {
        kprintf("[KPTI] FAIL: cannot map trampoline in kernel PML4\n");
        pmm_free_frame(trampoline_phys);
        return;
    }

    /* Mark the trampoline page as non-executable for data safety
     * (the entry/exit points are in the first 256 bytes which have
     *  exec permission from the CPU but data reads still work).
     *  We keep NX cleared; only kernel code can reach this page anyway. */
    /* (using default NX=0 is fine for a supervisor page) */

    /* 4. Patch the real handler address into the trampoline.
     *    The symbol syscall_entry_full is defined in syscall_asm.asm. */
    extern void syscall_entry_full(void);
    uint64_t handler_addr = (uint64_t)&syscall_entry_full;
    tramp_write(KPTI_TRAMP_OFF_EXIT_RIP, handler_addr);

    /* 5. Set LSTAR MSR to the trampoline entry point */
    uint64_t entry_addr = KPTI_TRAMPOLINE_VADDR + KPTI_TRAMP_OFF_ENTRY;
    uint32_t eax = (uint32_t)entry_addr;
    uint32_t edx = (uint32_t)(entry_addr >> 32);
    __asm__ volatile("wrmsr" :
        : "c" (0xC0000082), "a"(eax), "d"(edx));

    /* 6. Set SFMASK: mask IF (9), DF (10), TF (8), AC (18), IOPL (12-13) */
    uint64_t fmask = (1ULL<<9) | (1ULL<<10) | (1ULL<<8) | (1ULL<<18) | (3ULL<<12);
    __asm__ volatile("wrmsr" :
        : "c" (0xC0000084),
          "a"((uint32_t)fmask),
          "d"((uint32_t)(fmask >> 32)));

    /* 7. Update per-CPU trampoline CR3 values (boot CPU = 0) */
    uint64_t kernel_pml4_phys = VIRT_TO_PHYS((uint64_t)kernel_pml4);
    tramp_write(KPTI_TRAMP_OFF_CR3_KERN, kpti_cr3_kernel(kernel_pml4_phys));
    tramp_write(KPTI_TRAMP_OFF_CR3_USER, kpti_cr3_user(trampoline_phys));
    /* Note: user CR3 starts as a dummy (PCID 1); real user processes set theirs */

    kpti_active = 1;
    kprintf("[KPTI] Active — trampoline at phys 0x%llx, LSTAR → 0x%llx, handler → 0x%llx\n",
            (unsigned long long)trampoline_phys,
            (unsigned long long)entry_addr,
            (unsigned long long)handler_addr);
}

/* ── Create user PML4 for a process ──────────────────────────────────
 * Allocates a new PML4, copies user entries (0..255) from kernel PML4,
 * adds supervisor-only trampoline mapping.
 * Called from process_create_user(). */
int kpti_setup_process(struct process *proc) {
    if (!kpti_active || !proc->is_user) {
        proc->kpti_state.kernel_pml4 = NULL;
        proc->kpti_state.user_pml4 = NULL;
        proc->kpti_state.kernel_cr3 = 0;
        proc->kpti_state.user_cr3 = 0;
        return 0;
    }

    uint64_t *kernel_pml4 = vmm_get_pml4();      /* global kernel table (all kernel + user entries) */
    uint64_t kernel_pml4_phys = VIRT_TO_PHYS((uint64_t)kernel_pml4);

    /* 1. Allocate user PML4 — copy user half (0..255) from the process's table */
    uint64_t user_frame = pmm_alloc_frame();
    if (!user_frame) {
        kprintf("[KPTI] FAIL: cannot allocate user PML4 for PID %u\n", proc->pid);
        return -1;
    }
    uint64_t *user_pml4 = (uint64_t *)PHYS_TO_VIRT(user_frame);
    memset(user_pml4, 0, KPTI_PAGE_SIZE);

    /* Copy user-space PML4 entries (0..255) — the user half */
    memcpy(user_pml4, kernel_pml4, 256 * sizeof(uint64_t));

    /* 2. Build trampoline page table chain in user PML4.
     *    Need: PML4[511] → PDPT[511] → PD[511] → PT[0] → trampoline phys
     *
     *    Address bits for KPTI_TRAMPOLINE_VADDR (0x00007FFFFFFE0000):
     *      PML4: (addr >> 39) & 0x1FF = 0
     *      PDPT: (addr >> 30) & 0x1FF = 0x1FF = 511
     *      PD:   (addr >> 21) & 0x1FF = 0x1FF = 511
     *      PT:   (addr >> 12) & 0x1FF = 0x0E0 = 224
     *
     *    Wait — 0x00007FFFFFFE0000 is a USER address (bit 47 = 0).
     *    PML4 index = (0x7FFFFFFE0000 >> 39) & 0x1FF = 0xFF = 255
     *    PML4[255] covers 0x7F8000000000 - 0x7FFFFFFFFFFF
     *
     *    So for user-space trampoline address, PML4 entry = 255, not 511!
     *    This is GOOD — it's already in the user half range that we copied.
     *    But we need to add the mapping via the user PML4's page tables.
     */
    uint64_t pml4_idx = (KPTI_TRAMPOLINE_VADDR >> 39) & 0x1FF;
    uint64_t pdpt_idx = (KPTI_TRAMPOLINE_VADDR >> 30) & 0x1FF;
    uint64_t pd_idx   = (KPTI_TRAMPOLINE_VADDR >> 21) & 0x1FF;
    uint64_t pt_idx   = (KPTI_TRAMPOLINE_VADDR >> 12) & 0x1FF;

    /* The PML4[255] entry should be present (from the user half copy).
     * If it was present, get or create the PDPT. If the kernel didn't have
     * PML4[255] present (it shouldn't — kernel doesn't use that region),
     * we need to create it from scratch. */

    if (!(user_pml4[pml4_idx] & KPTI_PTE_PRESENT)) {
        /* Create PML4 entry for the trampoline area */
        uint64_t pdpt_phys = pmm_alloc_frame();
        if (!pdpt_phys) { pmm_free_frame(user_frame); return -1; }
        memset((void*)PHYS_TO_VIRT(pdpt_phys), 0, KPTI_PAGE_SIZE);
        user_pml4[pml4_idx] = pdpt_phys | KPTI_PTE_PRESENT | KPTI_PTE_WRITE;
    }

    /* Navigate through page tables, creating each level */
    uint64_t *pdpt = (uint64_t *)PHYS_TO_VIRT(user_pml4[pml4_idx] & KPTI_PTE_ADDR_MASK);
    if (!(pdpt[pdpt_idx] & KPTI_PTE_PRESENT)) {
        uint64_t pd_phys = pmm_alloc_frame();
        if (!pd_phys) { pmm_free_frame(user_frame); return -1; }
        memset((void*)PHYS_TO_VIRT(pd_phys), 0, KPTI_PAGE_SIZE);
        pdpt[pdpt_idx] = pd_phys | KPTI_PTE_PRESENT | KPTI_PTE_WRITE;
    }

    uint64_t *pd = (uint64_t *)PHYS_TO_VIRT(pdpt[pdpt_idx] & KPTI_PTE_ADDR_MASK);
    if (!(pd[pd_idx] & KPTI_PTE_PRESENT)) {
        uint64_t pt_phys = pmm_alloc_frame();
        if (!pt_phys) { pmm_free_frame(user_frame); return -1; }
        memset((void*)PHYS_TO_VIRT(pt_phys), 0, KPTI_PAGE_SIZE);
        pd[pd_idx] = pt_phys | KPTI_PTE_PRESENT | KPTI_PTE_WRITE;
    }

    uint64_t *pt = (uint64_t *)PHYS_TO_VIRT(pd[pd_idx] & KPTI_PTE_ADDR_MASK);

    /* Map the trampoline page: supervisor-only, global, executable */
    pt[pt_idx] = trampoline_phys | KPTI_PTE_PRESENT | KPTI_PTE_GLOBAL;
    pt[pt_idx] &= ~KPTI_PTE_USER;  /* clear user bit — supervisor-only */

    /* 3. Fill KPTI state */
    proc->kpti_state.kernel_pml4 = kernel_pml4;
    proc->kpti_state.user_pml4 = user_pml4;
    proc->kpti_state.kernel_cr3 = kpti_cr3_kernel(kernel_pml4_phys);
    proc->kpti_state.user_cr3 = kpti_cr3_user(user_frame);

    /* 4. If this is the current process, update trampoline CR3 */
    if (proc == process_get_current()) {
        kpti_trampoline_patch_cr3(0, proc->kpti_state.kernel_cr3, proc->kpti_state.user_cr3);
    }

    kprintf("[KPTI] PID %u: user PML4 at phys 0x%llx, trampoline mapped\n",
            proc->pid, (unsigned long long)user_frame);
    return 0;
}

/* ── Teardown user PML4 ────────────────────────────────────────────── */
void kpti_teardown_process(struct process *proc) {
    if (!kpti_active || !proc->kpti_state.user_pml4) return;

    uint64_t *user_pml4 = proc->kpti_state.user_pml4;
    uint64_t pml4_idx = (KPTI_TRAMPOLINE_VADDR >> 39) & 0x1FF;
    uint64_t pdpt_idx = (KPTI_TRAMPOLINE_VADDR >> 30) & 0x1FF;
    uint64_t pd_idx   = (KPTI_TRAMPOLINE_VADDR >> 21) & 0x1FF;

    /* Free trampoline page table pages (if any were created for this PML4) */
    if (user_pml4[pml4_idx] & KPTI_PTE_PRESENT) {
        uint64_t *pdpt = (uint64_t *)PHYS_TO_VIRT(user_pml4[pml4_idx] & KPTI_PTE_ADDR_MASK);
        if (pdpt[pdpt_idx] & KPTI_PTE_PRESENT) {
            uint64_t *pd = (uint64_t *)PHYS_TO_VIRT(pdpt[pdpt_idx] & KPTI_PTE_ADDR_MASK);
            if (pd[pd_idx] & KPTI_PTE_PRESENT) {
                uint64_t pt_phys = pd[pd_idx] & KPTI_PTE_ADDR_MASK;
                pd[pd_idx] = 0;
                pmm_free_frame(pt_phys);
            }
            pdpt[pdpt_idx] = 0;
            pmm_free_frame(pdpt[pdpt_idx] & KPTI_PTE_ADDR_MASK);
            pdpt[pdpt_idx] = 0;
        }
        user_pml4[pml4_idx] |= KPTI_PTE_WRITE;  /* ensure writable */
        uint64_t pdpt_phys = user_pml4[pml4_idx] & KPTI_PTE_ADDR_MASK;
        user_pml4[pml4_idx] = 0;
        pmm_free_frame(pdpt_phys);
    }

    /* Free the user PML4 itself */
    uint64_t upml4_phys = VIRT_TO_PHYS((uint64_t)user_pml4);
    pmm_free_frame(upml4_phys);

    proc->kpti_state.kernel_pml4 = NULL;
    proc->kpti_state.user_pml4 = NULL;
    proc->kpti_state.kernel_cr3 = 0;
    proc->kpti_state.user_cr3 = 0;
}

/* ── Patch CR3 values in the trampoline page ───────────────────────── */
void kpti_trampoline_patch_cr3(int cpu, uint64_t kernel_cr3, uint64_t user_cr3) {
    (void)cpu;
    if (!kpti_active) return;
    tramp_write(KPTI_TRAMP_OFF_CR3_KERN, kernel_cr3);

    uint64_t old_user_cr3 = tramp_read(KPTI_TRAMP_OFF_CR3_USER);
    tramp_write(KPTI_TRAMP_OFF_CR3_USER, user_cr3);

    /* Flush stale PCID 1 TLB entries when switching to a different user PML4 */
    if (old_user_cr3 != user_cr3) {
        invpcid_flush_pcid(KPTI_PCID_USER);
    }
}

/* ── Query ─────────────────────────────────────────────────────────── */
int kpti_is_active(void) {
    return kpti_active;
}
