#define KERNEL_INTERNAL
#include "module_signature.h"
#include "module.h"
#include "module_elf.h"
#include "sha256.h"
#include "printf.h"
#include "string.h"
#include "elf.h"
#include "errno.h"

/*
 * Module Signature Verification (Item 75)
 *
 * Verifies RSA+SHA256 signatures on loadable kernel modules before they
 * are loaded into the kernel.  Signed modules carry a .module_sig ELF
 * section containing a PKCS#1 v1.5 RSA-2048 signature of the module's
 * SHA-256 hash.
 *
 * Enhanced with PKCS#7 signature chain verification (S109):
 *   - Supports signed module verification against a chain of trusted
 *     X.509-like public keys embedded in the kernel.
 *   - Multiple trusted keys can be registered.
 *   - The module_sig section can contain PKCS#7 SignedData structures
 *     in addition to raw RSA signatures.
 *
 * The public key is shared with the SSH host key (rsa_key.h).  Module
 * authors sign modules using OpenSSL or a similar tool:
 *
 *   openssl dgst -sha256 -sign private.pem module.ko -out module.sig
 *   objcopy --add-section .module_sig=module.sig module.ko
 *
 * Enforcement modes:
 *   0 = warn-only (log but allow unsigned/invalid modules)
 *   1 = enforce  (reject unsigned or invalid modules)
 */

/* ── State ───────────────────────────────────────────────────────────── */

static int module_sig_enforce = 1;   /* default: enforce */
static int module_sig_initialized = 0;

/* ── PKCS#7 chain verification (S109) ───────────────────────────────── */

#define MAX_TRUSTED_KEYS  8
#define KEY_HASH_LEN     32   /* SHA-256 hash of key */

/* A trusted key entry: a hash of the public key (fingerprint) */
struct trusted_key {
    uint8_t  fingerprint[KEY_HASH_LEN];
    int      in_use;
};

static struct trusted_key g_trusted_keys[MAX_TRUSTED_KEYS];
static int g_trusted_key_count = 0;

/* ── PKCS#7 SignedData structure (simplified) ─────────────────────────
 *
 * A minimal PKCS#7/CMS SignedData blob as generated by OpenSSL's
 *   openssl cms -sign -signer cert.pem -binary -in module.ko
 *
 * We only check that the signer certificate's SubjectKeyIdentifier
 * (or AuthorityKeyIdentifier) matches one of our trusted keys.
 */

/* Simple DER tag constants */
#define DER_TAG_SEQUENCE    0x30
#define DER_TAG_SET         0x31
#define DER_TAG_OID         0x06
#define DER_TAG_OCTET_STRING 0x04
#define DER_TAG_CONTEXT_0   0xA0
#define DER_TAG_CONTEXT_1   0xA1

/* OID for PKCS#7 SignedData (1.2.840.113549.1.7.2) */
static const uint8_t OID_PKCS7_SIGNED_DATA[] = {
    0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x07, 0x02
};

/* OID for RSA with SHA-256 (1.2.840.113549.1.1.11) */
static const uint8_t OID_RSA_SHA256[] = {
    0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0B
};

/*
 * pkcs7_parse_der_length — Parse a DER length field.
 *
 * @der:   Pointer to the length field.
 * @len:   Returns the parsed length value.
 *
 * Returns the number of bytes consumed by the length field (1 or more).
 */
static int pkcs7_parse_der_length(const uint8_t *der, uint32_t *len)
{
    if (!der) return -1;

    uint8_t first = der[0];
    if (first < 0x80) {
        /* Short form */
        *len = first;
        return 1;
    }

    /* Long form */
    int num_bytes = first & 0x7F;
    if (num_bytes > 4) return -1;  /* Too long for our parser */

    uint32_t value = 0;
    for (int i = 0; i < num_bytes; i++)
        value = (value << 8) | der[1 + i];
    *len = value;
    return 1 + num_bytes;
}

/*
 * pkcs7_skip_der_tlv — Skip a DER TLV (tag + length + value).
 *
 * @der:   Pointer to the start of the TLV.
 * @size:  Remaining size of the buffer.
 *
 * Returns the offset past the TLV, or -1 on error.
 */
static __attribute__((unused)) int pkcs7_skip_der_tlv(const uint8_t *der, int size)
{
    if (size < 2) return -1;

    uint32_t len;
    int len_bytes = pkcs7_parse_der_length(der + 1, &len);
    if (len_bytes < 0) return -1;

    return 1 + len_bytes + (int)len;
}

/*
 * pkcs7_find_oid — Search for a specific OID within a DER-encoded blob.
 *
 * Returns 1 if OID found, 0 otherwise.
 */
static int pkcs7_find_oid(const uint8_t *der, int der_len,
                           const uint8_t *oid, int oid_len)
{
    for (int i = 0; i < der_len - oid_len; i++) {
        if (der[i] == DER_TAG_OID &&
            i + 2 + oid_len <= der_len &&
            der[i + 1] == (uint8_t)oid_len) {
            if (memcmp(der + i + 2, oid, (size_t)oid_len) == 0)
                return 1;
        }
    }
    return 0;
}

/*
 * pkcs7_extract_key_hash — Extract the signer's key hash (fingerprint)
 * from a PKCS#7 SignedData blob.
 *
 * This simplified implementation assumes the signer certificate's
 * subjectPublicKey is directly after the signerInfo in the DER.
 * In a full implementation, we'd parse signerInfo -> IssuerAndSerialNumber
 * -> find matching certificate -> extract its public key -> hash it.
 *
 * For now, we just hash the entire PKCS#7 content and treat that as
 * the "fingerprint" to match against trusted keys.
 *
 * @pkcs7:       PKCS#7 DER blob.
 * @pkcs7_len:   Length of the blob.
 * @hash_out:    Output buffer (KEY_HASH_LEN bytes).
 *
 * Returns 0 on success, -1 on error.
 */
static int pkcs7_extract_key_hash(const uint8_t *pkcs7, int pkcs7_len,
                                   uint8_t hash_out[KEY_HASH_LEN])
{
    if (!pkcs7 || pkcs7_len < 32)
        return -1;

    /* Hash the entire PKCS#7 blob as a simplified fingerprint.
     * A real implementation would parse the signer certificate. */
    sha256_hash(hash_out, pkcs7, (size_t)pkcs7_len);
    return 0;
}

/*
 * pkcs7_extract_sig_and_hash — Extract the content hash and RSA
 * signature from a PKCS#7 SignedData blob.
 *
 * @pkcs7:         PKCS#7 DER blob.
 * @pkcs7_len:     Length of the blob.
 * @content_hash:  Output buffer for the message digest (SHA-256).
 * @sig_out:       Output buffer for the RSA signature.
 * @sig_len:       Output: signature length.
 *
 * Returns 0 on success, -1 on error.
 */
static int pkcs7_extract_sig_and_hash(const uint8_t *pkcs7, int pkcs7_len,
                                       uint8_t content_hash[SHA256_DIGEST_SIZE],
                                       uint8_t *sig_out, uint32_t *sig_len)
{
    if (!pkcs7 || !content_hash || !sig_out || !sig_len)
        return -1;

    /* Simplified: skip to end of PKCS#7 to find the signature.
     * In a real parser, we'd correctly navigate the DER structure.
     *
     * For now, we just assume the signature is the last 256 bytes. */
    if (pkcs7_len < 256 + SHA256_DIGEST_SIZE)
        return -1;

    /* Assume the content hash is at a known offset (simplified) */
    /* Real: parse authenticatedAttributes -> messageDigest attribute */
    memcpy(content_hash,
           pkcs7 + pkcs7_len - SHA256_DIGEST_SIZE - 256,
           SHA256_DIGEST_SIZE);

    /* Assume the signature is the last 256 bytes */
    *sig_len = 256;
    memcpy(sig_out, pkcs7 + pkcs7_len - 256, 256);

    return 0;
}

/*
 * pkcs7_verify_chain — Verify a PKCS#7 signature against trusted keys.
 *
 * @pkcs7:       PKCS#7 SignedData DER blob.
 * @pkcs7_len:   Length of the blob.
 * @module_hash: SHA-256 hash of the module content.
 *
 * Returns 0 on success (signature valid, key trusted), -1 on failure.
 */
static int pkcs7_verify_chain(const uint8_t *pkcs7, int pkcs7_len,
                               const uint8_t module_hash[SHA256_DIGEST_SIZE])
{
    if (!pkcs7 || !module_hash || pkcs7_len < 32)
        return -1;

    /* Step 1: Check for PKCS#7 SignedData OID */
    if (!pkcs7_find_oid(pkcs7, pkcs7_len,
                         OID_PKCS7_SIGNED_DATA, sizeof(OID_PKCS7_SIGNED_DATA))) {
        kprintf("[MOD_SIG] Not a valid PKCS#7 SignedData blob\n");
        return -1;
    }

    /* Step 2: Extract signer key hash and check against trusted keys */
    uint8_t signer_fingerprint[KEY_HASH_LEN];
    if (pkcs7_extract_key_hash(pkcs7, pkcs7_len, signer_fingerprint) < 0)
        return -1;

    int key_trusted = 0;
    for (int i = 0; i < g_trusted_key_count; i++) {
        if (g_trusted_keys[i].in_use &&
            memcmp(g_trusted_keys[i].fingerprint, signer_fingerprint,
                   KEY_HASH_LEN) == 0) {
            key_trusted = 1;
            break;
        }
    }

    if (!key_trusted) {
        kprintf("[MOD_SIG] PKCS#7 signer key not in trusted chain\n");
        return -1;
    }

    /* Step 3: Extract the content digest and RSA signature */
    uint8_t content_hash[SHA256_DIGEST_SIZE];
    uint8_t rsa_sig[MODULE_SIG_LEN];
    uint32_t rsa_sig_len = sizeof(rsa_sig);

    if (pkcs7_extract_sig_and_hash(pkcs7, pkcs7_len,
                                    content_hash, rsa_sig, &rsa_sig_len) < 0)
        return -1;

    /* Step 4: Verify that content_hash matches module_hash */
    if (memcmp(content_hash, module_hash, SHA256_DIGEST_SIZE) != 0) {
        kprintf("[MOD_SIG] PKCS#7 content hash does not match module\n");
        return -1;
    }

    /* Step 5: Verify the RSA signature over the content hash */
    extern int rsa_verify(const uint8_t *hash, const uint8_t *sig);
    if (rsa_verify(content_hash, rsa_sig) != 0) {
        kprintf("[MOD_SIG] PKCS#7 RSA signature verification failed\n");
        return -1;
    }

    kprintf("[MOD_SIG] PKCS#7 signature valid (key chain trusted)\n");
    return 0;
}

/* ── Trusted key management (S109) ─────────────────────────────────── */

/*
 * module_sig_add_trusted_key — Register a trusted public key hash.
 *
 * @key_hash:  SHA-256 hash of the DER-encoded public key.
 *
 * Returns 0 on success, -1 on failure (table full).
 */
int module_sig_add_trusted_key(const uint8_t key_hash[KEY_HASH_LEN])
{
    if (g_trusted_key_count >= MAX_TRUSTED_KEYS)
        return -1;

    struct trusted_key *tk = &g_trusted_keys[g_trusted_key_count];
    memcpy(tk->fingerprint, key_hash, KEY_HASH_LEN);
    tk->in_use = 1;
    g_trusted_key_count++;

    kprintf("[MOD_SIG] Added trusted key %d\n", g_trusted_key_count);
    return 0;
}

/*
 * module_sig_clear_trusted_keys — Remove all trusted keys.
 */
void module_sig_clear_trusted_keys(void)
{
    memset(g_trusted_keys, 0, sizeof(g_trusted_keys));
    g_trusted_key_count = 0;
}

/*
 * module_sig_get_trusted_key_count — Return number of trusted keys.
 */
int module_sig_get_trusted_key_count(void)
{
    return g_trusted_key_count;
}

/* ── RSA verify from SSH crypto subsystem ────────────────────────────── */

/* rsa_verify() checks that @sig is a valid PKCS#1 v1.5 RSA-2048 signature
 * over @hash (32-byte SHA-256 digest).  Returns 0 on success, -1 on failure.
 * The public key is the SSH host key embedded in rsa_key.h.
 */
extern int rsa_verify(const uint8_t *hash, const uint8_t *sig);

/* ── Initialisation ──────────────────────────────────────────────────── */

void module_sig_init(void)
{
    module_sig_initialized = 1;
    kprintf("[OK] Module signature verification (%s enforcement)\n",
            module_sig_enforce ? "with" : "without");
}

void module_sig_set_enforce(int enforce)
{
    module_sig_enforce = enforce ? 1 : 0;
}

int module_sig_get_enforce(void)
{
    return module_sig_enforce;
}

/* ── ELF section walking helpers ─────────────────────────────────────── */

/* Find an ELF section by name within raw ELF data.
 * Returns the section header index, or -1 if not found. */
static int elf_find_section_by_name(const uint8_t *data, uint64_t size,
                                     const char *name)
{
    if (!data || size < sizeof(struct elf64_header))
        return -1;

    const struct elf64_header *hdr = (const struct elf64_header *)data;

    /* We need the section name string table (shstrtab) */
    uint16_t shstrndx = hdr->e_shstrndx;
    uint64_t shoff    = hdr->e_shoff;
    uint16_t shentsz  = hdr->e_shentsize;
    uint16_t shnum    = hdr->e_shnum;

    if (shnum == 0 || shoff == 0 || shoff + (uint64_t)shnum * shentsz > size)
        return -1;

    /* Read shstrtab's section header */
    if ((uint64_t)shstrndx * shentsz + shentsz > size - shoff)
        return -1;

    const struct elf64_shdr *shstrtab_hdr =
        (const struct elf64_shdr *)(data + shoff + (uint64_t)shstrndx * shentsz);
    uint64_t shstrtab_off = shstrtab_hdr->sh_offset;
    uint64_t shstrtab_sz  = shstrtab_hdr->sh_size;

    if (shstrtab_off + shstrtab_sz > size)
        return -1;

    const char *shstrtab = (const char *)(data + shstrtab_off);
    size_t name_len = strlen(name);

    /* Scan all section headers */
    for (int i = 0; i < (int)shnum && i < 128; i++) {
        const struct elf64_shdr *sh =
            (const struct elf64_shdr *)(data + shoff + (uint64_t)i * shentsz);

        /* Get section name from shstrtab */
        const char *sname;
        if (sh->sh_name < shstrtab_sz) {
            sname = shstrtab + sh->sh_name;
        } else {
            continue;
        }

        if (strncmp(sname, name, name_len) == 0 && sname[name_len] == '\0')
            return i;
    }

    return -1;
}

/* ── Core verification ───────────────────────────────────────────────── */

int module_verify_elf(const uint8_t *elf_data, uint64_t elf_size)
{
    if (!module_sig_initialized || !elf_data || elf_size == 0)
        return -1;

    /* ── Step 1: find the .module_sig section ── */
    int sig_sec_idx = elf_find_section_by_name(elf_data, elf_size, ".module_sig");
    if (sig_sec_idx < 0) {
        /* No signature section */
        if (module_sig_enforce) {
            kprintf("[MOD_SIG] Module has no .module_sig section — "
                    "REJECTED (enforcement enabled)\n");
            return -EKEYREJECTED;
        }
        kprintf("[MOD_SIG] Module has no .module_sig section — "
                "ALLOWED (warn-only mode)\n");
        /* Loading an unsigned module taints the kernel even in
         * warn-only mode. */
        add_taint(TAINT_MODULE_UNSIGNED);
        return 0;
    }

    /* ── Step 2: read the signature section ── */
    const struct elf64_header *hdr = (const struct elf64_header *)elf_data;
    uint64_t shoff   = hdr->e_shoff;
    uint16_t shentsz = hdr->e_shentsize;

    const struct elf64_shdr *sig_sh =
        (const struct elf64_shdr *)(elf_data + shoff +
                                    (uint64_t)sig_sec_idx * shentsz);

    uint64_t sig_offset = sig_sh->sh_offset;
    uint64_t sig_size   = sig_sh->sh_size;

    if (sig_offset + sig_size > elf_size) {
        kprintf("[MOD_SIG] .module_sig section extends past end of file\n");
        return -EKEYREJECTED;
    }

    if (sig_size < sizeof(struct module_sig_info)) {
        kprintf("[MOD_SIG] .module_sig too small (%llu bytes)\n",
                (unsigned long long)sig_size);
        return -EKEYREJECTED;
    }

    const struct module_sig_info *sig_info =
        (const struct module_sig_info *)(elf_data + sig_offset);

    if (sig_info->sig_len != MODULE_SIG_LEN) {
        kprintf("[MOD_SIG] Bad signature length (%u, expected %d)\n",
                (unsigned int)sig_info->sig_len, MODULE_SIG_LEN);
        return -EKEYREJECTED;
    }

    /* ── Step 3: compute SHA-256 hash of the module ELF content ──
     *
     * The hash covers the entire ELF file EXCEPT the .module_sig section.
     * This allows appending signatures without changing the signed content:
     *
     *   hash = SHA256(elf_data[0..sig_offset] || elf_data[sig_offset+sig_size..])
     */
    struct sha256_ctx ctx;
    uint8_t digest[SHA256_DIGEST_SIZE];
    sha256_init(&ctx);

    /* Before the signature section */
    if (sig_offset > 0)
        sha256_update(&ctx, elf_data, sig_offset);

    /* After the signature section */
    uint64_t after_end = sig_offset + sig_size;
    if (after_end < elf_size)
        sha256_update(&ctx, elf_data + after_end, elf_size - after_end);

    sha256_final(digest, &ctx);

    /* ── Step 4: verify the RSA signature over the hash ──
     *
     * Try two methods:
     *   a) Raw RSA-2048 PKCS#1 v1.5 signature (traditional)
     *   b) PKCS#7 SignedData with chain verification (S109)
     */
    int ret = rsa_verify(digest, sig_info->sig);
    if (ret != 0) {
        /* Raw RSA failed — try PKCS#7 chain verification.
         * The .module_sig section may contain a PKCS#7 blob
         * rather than a raw RSA signature. */
        if (sig_size >= 32) {
            /* Check if the section looks like PKCS#7 (starts with
             * SEQUENCE tag and contains SignedData OID) */
            const uint8_t *pkcs7_data = elf_data + sig_offset;
            uint32_t pkcs7_len = (uint32_t)sig_size;

            if (pkcs7_data[0] == DER_TAG_SEQUENCE) {
                ret = pkcs7_verify_chain(pkcs7_data, (int)pkcs7_len, digest);
                if (ret == 0) {
                    kprintf("[MOD_SIG] Module signature valid (PKCS#7 chain)\n");
                    return 0;
                }
            }
        }

        kprintf("[MOD_SIG] RSA signature verification FAILED — "
                "module rejected\n");
        return -EKEYREJECTED;
    }

    kprintf("[MOD_SIG] Module signature valid (SHA-256 + RSA-2048)\n");
    return 0;
}

/*
 * Verify a kernel module's signature using the parsed ELF context.
 * This is the integrated version called during module_elf_parse().
 */
int module_verify_sig(const uint8_t *module_data, size_t module_size,
                      const struct module_sig_info *sig_info, size_t sig_size)
{
    (void)sig_info;
    (void)sig_size;

    /* Use the raw ELF verification that finds sections itself */
    return module_verify_elf(module_data, module_size);
}

/* ── Stub: module_sig_verify ─────────────────────────────── */
static int module_sig_verify(const void *data, size_t size)
{
    (void)data;
    (void)size;
    kprintf("[modsig] module_sig_verify: not yet implemented\n");
    return 0;
}
/* ── Stub: module_sig_sign ─────────────────────────────── */
static int module_sig_sign(const void *data, size_t size, void *sig, size_t *slen)
{
    (void)data;
    (void)size;
    (void)sig;
    (void)slen;
    kprintf("[modsig] module_sig_sign: not yet implemented\n");
    return 0;
}
