#!/usr/bin/env python3
"""Generate src/shell/cli_test.c with embedded CLI test script."""
import os

cmds_dir = "src/shell/cmds"
cmds = sorted(f[4:-2] for f in os.listdir(cmds_dir) if f.startswith("cmd_") and f.endswith(".c"))

lines = []
lines.append('/* Auto-generated by src/test/test_cli.py */')
lines.append('#include "shell.h"')
lines.append('#include "shell_cmd_table.h"')
lines.append('#include "printf.h"')
lines.append('')
lines.append('static const char *all_cmds[] = {')
for name in cmds:
    lines.append(f'    "{name}",')
lines.append('};')
lines.append('')
lines.append('void cli_test_run(void) {')
lines.append('    int i, pass = 0, fail = 0;')
lines.append('    kprintf("=== CLI_TESTS_START ===\\n");')
lines.append('    for (i = 0; i < (int)(sizeof(all_cmds)/sizeof(all_cmds[0])); i++) {')
lines.append('        if (shell_cmd_lookup_fn(all_cmds[i]))')
lines.append('            pass++;')
lines.append('        else {')
lines.append('            kprintf("  fail: ");')
lines.append('            kprintf(all_cmds[i]);')
lines.append('            kprintf("\\n");')
lines.append('            fail++;')
lines.append('        }')
lines.append('    }')
lines.append('    kprintf("=== CLI_TESTS_DONE ===\\n");')
lines.append('}')

with open("src/shell/cli_test.c", "w") as f:
    f.write('\n'.join(lines) + '\n')
print(f"Generated {len(cmds)} CLI tests in src/shell/cli_test.c")
