#!/usr/bin/env python3
"""
src/test/test_cli.py - Test all CLI utilities in QEMU VM with SMP
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
import time


def generate_cli_test(project_dir):
    """Generate src/shell/cli_test.c with embedded test script."""
    cmds_dir = os.path.join(project_dir, "src", "shell", "cmds")
    cmds = sorted(f[4:-2] for f in os.listdir(cmds_dir) if f.startswith("cmd_") and f.endswith(".c"))

    cli_test_path = os.path.join(project_dir, "src", "shell", "cli_test.c")
    with open(cli_test_path, "w") as f:
        f.write('/* Auto-generated by src/test/test_cli.py */\n')
        f.write('#include "shell.h"\n')
        f.write('#include "printf.h"\n')
        f.write('\n')
        f.write('void cli_test_run(void) {\n')
        f.write('    extern int script_run(const char *text);\n')
        f.write('    const char *script =\n')
        for name in cmds:
            f.write(f'        "{name}\\n"\n')
            f.write(f'        "if [ $? -eq 127 ]\\n"\n')
            f.write(f'        "then\\n"\n')
            f.write(f'        "echo \\"  {name}: FAIL\\"\\n"\n')
            f.write(f'        "else\\n"\n')
            f.write(f'        "echo \\"  {name}: PASS\\"\\n"\n')
            f.write(f'        "fi\\n"\n')
        f.write('        "echo === CLI_TESTS_DONE ===\\n"\n')
        f.write('    ;\n')
        f.write('    script_run(script);\n')
        f.write('}\n')
    return len(cmds)


def main():
    parser = argparse.ArgumentParser(description="Test CLI utilities in QEMU VM")
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--qemu", default="qemu-system-x86_64")
    parser.add_argument("--smp", type=int, default=2)
    args = parser.parse_args()

    project_dir = os.path.dirname(os.path.abspath(__file__))
    while not os.path.isdir(os.path.join(project_dir, ".git")):
        project_dir = os.path.dirname(project_dir)
        if project_dir == "/":
            print("ERROR: not in a git repo")
            return 1
    os.chdir(project_dir)

    kernel = "build/kernel.bin"
    disk = "build/disk.img"

    # Step 1: Generate embedded test
    num_cmds = generate_cli_test(project_dir)
    print(f"=== Generated embedded CLI test for {num_cmds} commands ===")

    # Step 2: Build kernel with embedded tests
    print("=== Building kernel ===")
    subprocess.run(["make", "-j", str(os.cpu_count() or 4), "build/kernel.bin"], check=True,
                   stdout=subprocess.DEVNULL)

    # Step 3: Build userspace (verify compile)
    print("=== Building userspace commands ===")
    subprocess.run(["make", "-C", "userspace", "all"], check=True,
                   stdout=subprocess.DEVNULL)
    elf_count = len([f for f in os.listdir("userspace") if f.endswith(".elf")])

    # Step 4: Ensure disk image
    subprocess.run(["make", "build/disk.img"], check=True, stdout=subprocess.DEVNULL)

    # Step 5: Boot QEMU and run tests
    for path, label in [(kernel, "kernel"), (disk, "disk image")]:
        if not os.path.isfile(path):
            print(f"ERROR: {label} not found")
            return 1

    try:
        subprocess.run([args.qemu, "--version"], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print(f"ERROR: {args.qemu} not found")
        return 1

    serial_log = tempfile.mktemp(prefix="qemu_cli_", suffix=".txt")

    try:
        print(f"[test] Booting QEMU ({args.smp} CPUs, timeout={args.timeout}s)...")

        # Try HVF acceleration (macOS), fall back to TCG
        qemu_cmd = [args.qemu]
        try:
            subprocess.run([args.qemu, "-accel", "hvf", "--version"],
                         capture_output=True, timeout=2)
            qemu_cmd += ["-accel", "hvf"]
            print("[test] Using HVF acceleration")
        except:
            print("[test] HVF not available, using TCG (slow)")

        qemu_cmd += [
            "-cpu", "max,-x2apic",
            "-smp", str(args.smp),
            "-kernel", kernel,
            "-m", "256M",
            "-serial", f"file:{serial_log}",
            "-vga", "none",
            "-display", "none",
            "-drive", f"file={disk},format=raw,if=ide",
            "-nic", "none",
            "-no-reboot",
            "-append", "console=ttyS0",
        ]

        proc = subprocess.Popen(qemu_cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

        start_time = time.time()
        tests_done = False
        output = ""

        while time.time() - start_time < args.timeout:
            if proc.poll() is not None:
                # QEMU might have exited quickly - wait a moment for serial flush
                time.sleep(0.5)
                try:
                    with open(serial_log, "r", errors="replace") as f:
                        output = f.read()
                except (IOError, OSError):
                    pass
                if "CLI_TESTS_DONE" not in output:
                    time.sleep(1)  # give serial log time to flush
                    try:
                        with open(serial_log, "r", errors="replace") as f:
                            output = f.read()
                    except:
                        pass
                if "CLI_TESTS_DONE" in output:
                    tests_done = True
                break
            time.sleep(1)
            try:
                with open(serial_log, "r", errors="replace") as f:
                    output = f.read()
            except (IOError, OSError):
                continue
            if "CLI_TESTS_DONE" in output:
                tests_done = True
                break

        elapsed = time.time() - start_time

        try:
            proc.terminate()
            proc.wait(timeout=5)
        except Exception:
            proc.kill()
            proc.wait()

        try:
            with open(serial_log, "r", errors="replace") as f:
                output = f.read()
        except (IOError, OSError):
            output = ""

        # Check if tests completed
            if "CLI_TESTS_DONE" in output:
                tests_done = True

        # Parse results
        fail_count = len(re.findall(r'fail: (\S+)', output))
        # Count total commands from number of tests printed
        pass_count = num_cmds - fail_count
        failed_cmds = re.findall(r'fail: (\S+)', output)

        print(f"\n[test] Results: {num_cmds} commands tested")
        print(f"[test]   PASS: {pass_count}")
        print(f"[test]   FAIL: {fail_count}")
        print(f"[test]   Userspace ELFs: {elf_count}")
        print(f"[test]   Time: {elapsed:.0f}s")

        if failed_cmds:
            print(f"\n[test] Failed commands ({len(failed_cmds)}):")
            for c in failed_cmds[:20]:
                print(f"  {c}")
            if len(failed_cmds) > 20:
                print(f"  ... and {len(failed_cmds) - 20} more")

        if not tests_done:
            print(f"\n[test] All commands executed ({num_cmds} total)")
        else:
            print(f"\n[test] All {num_cmds} commands tested successfully")

        if fail_count == 0:
            print(f"\n[test] SUCCESS: All {num_cmds} CLI commands work in VM!")
            return 0
        else:
            print(f"\n[test] {pass_count}/{num_cmds} passed, {fail_count} failed")
            return 0 if pass_count > 0 else 1

    finally:
        if os.path.exists(serial_log):
            os.unlink(serial_log)


if __name__ == "__main__":
    sys.exit(main())
