/*
 * fm_synth.c — FM synthesis engine for MIDI playback
 *
 * Implements a software 2-operator FM synthesiser modelled after the
 * classic Yamaha OPL/OPL2 architecture.  Each voice is a carrier +
 * modulator pair where the modulator's output frequency-modulates the
 * carrier's phase to produce harmonically rich timbres.
 *
 * Key design:
 *   - 1024-entry sine lookup table (int16_t, pre-computed)
 *   - 32-bit phase accumulators (10-bit sine index + 22-bit fraction)
 *   - ADSR envelope per operator (attack/decay/sustain/release)
 *   - Polyphony: up to FM_SYNTH_MAX_VOICES simultaneous voices
 *   - Output: 16-bit signed PCM (mono or stereo interleaved)
 *   - All integer arithmetic (no floating point in hot path)
 *
 * The module registers itself with the MIDI sequencer so that
 * midi_seq_note_on/off events are automatically routed through
 * the FM synthesiser instead of the PC speaker.
 *
 * Task #11 — D142: MIDI synthesiser (FM synthesis baseline)
 */

#include "fm_synth.h"
#include "printf.h"
#include "string.h"
#include "heap.h"
#include "spinlock.h"
#include "errno.h"
#include "module.h"

/* ── Sine lookup table (1024 entries, pre-computed) ────────────────── */
/* Generated by: int(32767.0 * sin(2*pi * i / 1024)) for i=0..1023 */

static const int16_t g_fm_sine_table[FM_SYNTH_SINE_TABLE_SIZE] = {
        0,      201,      402,      603,      804,     1005,     1206,     1406,
     1607,     1808,     2009,     2209,     2410,     2610,     2811,     3011,
     3211,     3411,     3611,     3811,     4011,     4210,     4409,     4608,
     4807,     5006,     5205,     5403,     5601,     5799,     5997,     6195,
     6392,     6589,     6786,     6982,     7179,     7375,     7571,     7766,
     7961,     8156,     8351,     8545,     8739,     8932,     9126,     9319,
     9511,     9703,     9895,    10087,    10278,    10469,    10659,    10849,
    11038,    11227,    11416,    11604,    11792,    11980,    12166,    12353,
    12539,    12724,    12909,    13094,    13278,    13462,    13645,    13827,
    14009,    14191,    14372,    14552,    14732,    14911,    15090,    15268,
    15446,    15623,    15799,    15975,    16150,    16325,    16499,    16672,
    16845,    17017,    17189,    17360,    17530,    17699,    17868,    18036,
    18204,    18371,    18537,    18702,    18867,    19031,    19194,    19357,
    19519,    19680,    19840,    20000,    20159,    20317,    20474,    20631,
    20787,    20942,    21096,    21249,    21402,    21554,    21705,    21855,
    22004,    22153,    22301,    22448,    22594,    22739,    22883,    23027,
    23169,    23311,    23452,    23592,    23731,    23869,    24006,    24143,
    24278,    24413,    24546,    24679,    24811,    24942,    25072,    25201,
    25329,    25456,    25582,    25707,    25831,    25954,    26077,    26198,
    26318,    26437,    26556,    26673,    26789,    26905,    27019,    27132,
    27244,    27355,    27466,    27575,    27683,    27790,    27896,    28001,
    28105,    28208,    28309,    28410,    28510,    28608,    28706,    28802,
    28897,    28992,    29085,    29177,    29268,    29358,    29446,    29534,
    29621,    29706,    29790,    29873,    29955,    30036,    30116,    30195,
    30272,    30349,    30424,    30498,    30571,    30643,    30713,    30783,
    30851,    30918,    30984,    31049,    31113,    31175,    31236,    31297,
    31356,    31413,    31470,    31525,    31580,    31633,    31684,    31735,
    31785,    31833,    31880,    31926,    31970,    32014,    32056,    32097,
    32137,    32176,    32213,    32249,    32284,    32318,    32350,    32382,
    32412,    32441,    32468,    32495,    32520,    32544,    32567,    32588,
    32609,    32628,    32646,    32662,    32678,    32692,    32705,    32717,
    32727,    32736,    32744,    32751,    32757,    32761,    32764,    32766,
    32767,    32766,    32764,    32761,    32757,    32751,    32744,    32736,
    32727,    32717,    32705,    32692,    32678,    32662,    32646,    32628,
    32609,    32588,    32567,    32544,    32520,    32495,    32468,    32441,
    32412,    32382,    32350,    32318,    32284,    32249,    32213,    32176,
    32137,    32097,    32056,    32014,    31970,    31926,    31880,    31833,
    31785,    31735,    31684,    31633,    31580,    31525,    31470,    31413,
    31356,    31297,    31236,    31175,    31113,    31049,    30984,    30918,
    30851,    30783,    30713,    30643,    30571,    30498,    30424,    30349,
    30272,    30195,    30116,    30036,    29955,    29873,    29790,    29706,
    29621,    29534,    29446,    29358,    29268,    29177,    29085,    28992,
    28897,    28802,    28706,    28608,    28510,    28410,    28309,    28208,
    28105,    28001,    27896,    27790,    27683,    27575,    27466,    27355,
    27244,    27132,    27019,    26905,    26789,    26673,    26556,    26437,
    26318,    26198,    26077,    25954,    25831,    25707,    25582,    25456,
    25329,    25201,    25072,    24942,    24811,    24679,    24546,    24413,
    24278,    24143,    24006,    23869,    23731,    23592,    23452,    23311,
    23169,    23027,    22883,    22739,    22594,    22448,    22301,    22153,
    22004,    21855,    21705,    21554,    21402,    21249,    21096,    20942,
    20787,    20631,    20474,    20317,    20159,    20000,    19840,    19680,
    19519,    19357,    19194,    19031,    18867,    18702,    18537,    18371,
    18204,    18036,    17868,    17699,    17530,    17360,    17189,    17017,
    16845,    16672,    16499,    16325,    16150,    15975,    15799,    15623,
    15446,    15268,    15090,    14911,    14732,    14552,    14372,    14191,
    14009,    13827,    13645,    13462,    13278,    13094,    12909,    12724,
    12539,    12353,    12166,    11980,    11792,    11604,    11416,    11227,
    11038,    10849,    10659,    10469,    10278,    10087,     9895,     9703,
     9511,     9319,     9126,     8932,     8739,     8545,     8351,     8156,
     7961,     7766,     7571,     7375,     7179,     6982,     6786,     6589,
     6392,     6195,     5997,     5799,     5601,     5403,     5205,     5006,
     4807,     4608,     4409,     4210,     4011,     3811,     3611,     3411,
     3211,     3011,     2811,     2610,     2410,     2209,     2009,     1808,
     1607,     1406,     1206,     1005,      804,      603,      402,      201,
        0,     -201,     -402,     -603,     -804,    -1005,    -1206,    -1406,
    -1607,    -1808,    -2009,    -2209,    -2410,    -2610,    -2811,    -3011,
    -3211,    -3411,    -3611,    -3811,    -4011,    -4210,    -4409,    -4608,
    -4807,    -5006,    -5205,    -5403,    -5601,    -5799,    -5997,    -6195,
    -6392,    -6589,    -6786,    -6982,    -7179,    -7375,    -7571,    -7766,
    -7961,    -8156,    -8351,    -8545,    -8739,    -8932,    -9126,    -9319,
    -9511,    -9703,    -9895,   -10087,   -10278,   -10469,   -10659,   -10849,
   -11038,   -11227,   -11416,   -11604,   -11792,   -11980,   -12166,   -12353,
   -12539,   -12724,   -12909,   -13094,   -13278,   -13462,   -13645,   -13827,
   -14009,   -14191,   -14372,   -14552,   -14732,   -14911,   -15090,   -15268,
   -15446,   -15623,   -15799,   -15975,   -16150,   -16325,   -16499,   -16672,
   -16845,   -17017,   -17189,   -17360,   -17530,   -17699,   -17868,   -18036,
   -18204,   -18371,   -18537,   -18702,   -18867,   -19031,   -19194,   -19357,
   -19519,   -19680,   -19840,   -20000,   -20159,   -20317,   -20474,   -20631,
   -20787,   -20942,   -21096,   -21249,   -21402,   -21554,   -21705,   -21855,
   -22004,   -22153,   -22301,   -22448,   -22594,   -22739,   -22883,   -23027,
   -23169,   -23311,   -23452,   -23592,   -23731,   -23869,   -24006,   -24143,
   -24278,   -24413,   -24546,   -24679,   -24811,   -24942,   -25072,   -25201,
   -25329,   -25456,   -25582,   -25707,   -25831,   -25954,   -26077,   -26198,
   -26318,   -26437,   -26556,   -26673,   -26789,   -26905,   -27019,   -27132,
   -27244,   -27355,   -27466,   -27575,   -27683,   -27790,   -27896,   -28001,
   -28105,   -28208,   -28309,   -28410,   -28510,   -28608,   -28706,   -28802,
   -28897,   -28992,   -29085,   -29177,   -29268,   -29358,   -29446,   -29534,
   -29621,   -29706,   -29790,   -29873,   -29955,   -30036,   -30116,   -30195,
   -30272,   -30349,   -30424,   -30498,   -30571,   -30643,   -30713,   -30783,
   -30851,   -30918,   -30984,   -31049,   -31113,   -31175,   -31236,   -31297,
   -31356,   -31413,   -31470,   -31525,   -31580,   -31633,   -31684,   -31735,
   -31785,   -31833,   -31880,   -31926,   -31970,   -32014,   -32056,   -32097,
   -32137,   -32176,   -32213,   -32249,   -32284,   -32318,   -32350,   -32382,
   -32412,   -32441,   -32468,   -32495,   -32520,   -32544,   -32567,   -32588,
   -32609,   -32628,   -32646,   -32662,   -32678,   -32692,   -32705,   -32717,
   -32727,   -32736,   -32744,   -32751,   -32757,   -32761,   -32764,   -32766,
   -32767,   -32766,   -32764,   -32761,   -32757,   -32751,   -32744,   -32736,
   -32727,   -32717,   -32705,   -32692,   -32678,   -32662,   -32646,   -32628,
   -32609,   -32588,   -32567,   -32544,   -32520,   -32495,   -32468,   -32441,
   -32412,   -32382,   -32350,   -32318,   -32284,   -32249,   -32213,   -32176,
   -32137,   -32097,   -32056,   -32014,   -31970,   -31926,   -31880,   -31833,
   -31785,   -31735,   -31684,   -31633,   -31580,   -31525,   -31470,   -31413,
   -31356,   -31297,   -31236,   -31175,   -31113,   -31049,   -30984,   -30918,
   -30851,   -30783,   -30713,   -30643,   -30571,   -30498,   -30424,   -30349,
   -30272,   -30195,   -30116,   -30036,   -29955,   -29873,   -29790,   -29706,
   -29621,   -29534,   -29446,   -29358,   -29268,   -29177,   -29085,   -28992,
   -28897,   -28802,   -28706,   -28608,   -28510,   -28410,   -28309,   -28208,
   -28105,   -28001,   -27896,   -27790,   -27683,   -27575,   -27466,   -27355,
   -27244,   -27132,   -27019,   -26905,   -26789,   -26673,   -26556,   -26437,
   -26318,   -26198,   -26077,   -25954,   -25831,   -25707,   -25582,   -25456,
   -25329,   -25201,   -25072,   -24942,   -24811,   -24679,   -24546,   -24413,
   -24278,   -24143,   -24006,   -23869,   -23731,   -23592,   -23452,   -23311,
   -23169,   -23027,   -22883,   -22739,   -22594,   -22448,   -22301,   -22153,
   -22004,   -21855,   -21705,   -21554,   -21402,   -21249,   -21096,   -20942,
   -20787,   -20631,   -20474,   -20317,   -20159,   -20000,   -19840,   -19680,
   -19519,   -19357,   -19194,   -19031,   -18867,   -18702,   -18537,   -18371,
   -18204,   -18036,   -17868,   -17699,   -17530,   -17360,   -17189,   -17017,
   -16845,   -16672,   -16499,   -16325,   -16150,   -15975,   -15799,   -15623,
   -15446,   -15268,   -15090,   -14911,   -14732,   -14552,   -14372,   -14191,
   -14009,   -13827,   -13645,   -13462,   -13278,   -13094,   -12909,   -12724,
   -12539,   -12353,   -12166,   -11980,   -11792,   -11604,   -11416,   -11227,
   -11038,   -10849,   -10659,   -10469,   -10278,   -10087,    -9895,    -9703,
    -9511,    -9319,    -9126,    -8932,    -8739,    -8545,    -8351,    -8156,
    -7961,    -7766,    -7571,    -7375,    -7179,    -6982,    -6786,    -6589,
    -6392,    -6195,    -5997,    -5799,    -5601,    -5403,    -5205,    -5006,
    -4807,    -4608,    -4409,    -4210,    -4011,    -3811,    -3611,    -3411,
    -3211,    -3011,    -2811,    -2610,    -2410,    -2209,    -2009,    -1808,
    -1607,    -1406,    -1206,    -1005,     -804,     -603,     -402,     -201,
};

/* ── MIDI note phase increment table (128 notes, 44.1 kHz) ─────────── */
/* Computed as: phase_inc[n] = (uint32_t)(440 * 2^((n-69)/12) / 44100 * 2^32) */

static const uint32_t g_fm_phase_incs[128] = {
     796253,     843601,     893764,     946910,    1003216,    1062871,    1126072,    1193032,
    1263973,    1339133,    1418762,    1503126,    1592507,    1687202,    1787529,    1893821,
    2006433,    2125742,    2252145,    2386065,    2527947,    2678267,    2837525,    3006253,
    3185014,    3374405,    3575058,    3787642,    4012867,    4251484,    4504291,    4772130,
    5055895,    5356535,    5675051,    6012507,    6370029,    6748811,    7150116,    7575284,
    8025734,    8502969,    9008582,    9544260,   10111791,   10713070,   11350102,   12025014,
   12740059,   13497622,   14300233,   15150569,   16051469,   17005939,   18017164,   19088521,
   20223583,   21426140,   22700205,   24050029,   25480118,   26995245,   28600466,   30301138,
   32102938,   34011878,   36034329,   38177042,   40447167,   42852281,   45400410,   48100059,
   50960237,   53990491,   57200933,   60602277,   64205876,   68023756,   72068659,   76354085,
   80894335,   85704562,   90800821,   96200119,  101920475,  107980982,  114401866,  121204555,
  128411752,  136047513,  144137319,  152708170,  161788670,  171409125,  181601642,  192400238,
  203840951,  215961965,  228803732,  242409110,  256823505,  272095026,  288274638,  305416340,
  323577341,  342818251,  363203285,  384800476,  407681903,  431923931,  457607464,  484818220,
  513647011,  544190052,  576549277,  610832681,  647154682,  685636502,  726406570,  769600953,
  815363807,  863847862,  915214929,  969636440, 1027294023, 1088380105, 1153098554, 1221665362,
};

/* ── Global FM synthesiser state ───────────────────────────────────── */

struct fm_synth g_fm_synth;

static spinlock_t g_fm_lock;

/* ── Internal helpers ─────────────────────────────────────────────── */

/**
 * fm_rate_to_time — Convert ADSR rate (0–255) to sample count.
 *
 * Higher rate = shorter time (faster envelope).  The max_ms parameter
 * sets the duration for rate=0.  Minimum returned is ~1 ms (44 samples
 * at 44.1 kHz).
 *
 * @rate:    Envelope rate value (0–255, 255=fastest).
 * @sr:      Sample rate in Hz.
 * @max_ms:  Maximum envelope duration in ms (for rate=0).
 *
 * Returns the sample count, clamped to uint16_t range.
 */
static uint16_t fm_rate_to_time(uint8_t rate, uint32_t sr, uint32_t max_ms)
{
    uint32_t t = sr * max_ms / 1000U;            /* max samples */
    t = t * (255U - (uint32_t)rate) / 255U;      /* scale by rate */
    if (t < 44U) t = 44U;                        /* minimum ~1 ms */
    if (t > 65535U) t = 65535U;                  /* clamp */
    return (uint16_t)t;
}

/**
 * fm_sine_lookup — Look up a sine value from the table.
 *
 * @phase:  32-bit phase accumulator (upper 10 bits = index).
 *
 * Returns the 16-bit signed sine value (-32767 .. 32767).
 */
static inline int16_t fm_sine_lookup(uint32_t phase)
{
    uint32_t idx = (phase >> FM_SYNTH_PHASE_FRAC_BITS) & FM_SYNTH_SINE_MASK;
    return g_fm_sine_table[idx];
}

/**
 * fm_waveform_lookup — Generate a sample for the given waveform type.
 *
 * @phase:  32-bit phase accumulator.
 * @wave:   Waveform type (FM_WAVE_SINE, etc.).
 * @lfsr:   Pointer to noise LFSR state (used for FM_WAVE_NOISE).
 *
 * Returns a 16-bit signed sample value (-32767 .. 32767).
 */
static inline int16_t fm_waveform_lookup(uint32_t phase,
                                          uint8_t wave,
                                          uint16_t *lfsr)
{
    switch (wave) {
    case FM_WAVE_SINE:
        return fm_sine_lookup(phase);

    case FM_WAVE_SQUARE: {
        /* Square wave: sign of sine (or just use table sign bit) */
        uint32_t idx = (phase >> FM_SYNTH_PHASE_FRAC_BITS) & 0x3FFU;
        return (idx < 512U) ? 32767 : -32767;
    }

    case FM_WAVE_SAWTOOTH: {
        /* Sawtooth: linear ramp from -32767 to +32767 per cycle */
        uint32_t idx = phase >> (FM_SYNTH_PHASE_FRAC_BITS + 2U);
        return (int16_t)((int32_t)(idx & 0xFFU) * 257 - 32767);
    }

    case FM_WAVE_NOISE: {
        /* 16-bit LFSR (x^16 + x^14 + x^13 + x^11 + 1) */
        uint16_t feedback = 0U;
        feedback ^= (*lfsr >> 15) ^ (*lfsr >> 13);
        feedback ^= (*lfsr >> 12) ^ (*lfsr >> 10);
        *lfsr = (uint16_t)((*lfsr << 1) | (feedback & 1U));
        /* Scale LFSR to [-32767, 32767] */
        int32_t val = (int32_t)(*lfsr) - 32768;
        return (int16_t)(val * 2);
    }

    default:
        return fm_sine_lookup(phase);
    }
}

/* ── Envelope processing ───────────────────────────────────────────── */

/**
 * fm_env_update — Advance the envelope by one sample.
 *
 * Updates env_state and env_level based on the current ADSR phase.
 * Returns 1 if the operator is still audible, 0 if it has finished
 * the release phase and should be silenced.
 */
static int fm_env_update(struct fm_operator *op)
{
    uint32_t env_phase;

    /* env_level is uint8_t (0-255), no clamp needed */

    switch (op->env_state) {
    case FM_ENV_IDLE:
        op->env_level = 0;
        return 0;

    case FM_ENV_ATTACK:
        /* Linear ramp from 0 to 255 over attack_time samples */
        if (op->attack_time == 0) {
            op->env_level = 255;
            op->env_state = FM_ENV_DECAY;
            break;
        }
        env_phase = op->env_phase;
        if (env_phase >= op->attack_time) {
            op->env_level = 255;
            op->env_phase = 0;
            op->env_state = FM_ENV_DECAY;
        } else {
            op->env_level = (uint8_t)(env_phase * 255U / op->attack_time);
            op->env_phase = env_phase + 1;
        }
        break;

    case FM_ENV_DECAY:
        /* Linear fall from 255 to sustain_level over decay_time samples */
        if (op->decay_time == 0) {
            op->env_level = op->sustain_level;
            op->env_state = FM_ENV_SUSTAIN;
            break;
        }
        env_phase = op->env_phase;
        if (env_phase >= op->decay_time) {
            op->env_level = op->sustain_level;
            op->env_phase = 0;
            op->env_state = FM_ENV_SUSTAIN;
        } else {
            uint32_t decay_progress = env_phase * 255U / op->decay_time;
            uint32_t range = 255U - (uint32_t)op->sustain_level;
            op->env_level = (uint8_t)(255U - (decay_progress * range / 255U));
            op->env_phase = env_phase + 1;
        }
        break;

    case FM_ENV_SUSTAIN:
        /* Hold at sustain level */
        op->env_level = op->sustain_level;
        break;

    case FM_ENV_RELEASE:
        /* Linear fall from current level to 0 over release_time samples */
        if (op->release_time == 0) {
            op->env_level = 0;
            op->env_state = FM_ENV_IDLE;
            return 0;
        }
        env_phase = op->env_phase;
        if (env_phase >= op->release_time) {
            op->env_level = 0;
            op->env_state = FM_ENV_IDLE;
            return 0;
        }
        {
            /* Compute remaining level */
            uint32_t remaining = (op->release_time - env_phase) * 255U / op->release_time;
            op->env_level = (uint8_t)remaining;
            op->env_phase = env_phase + 1;
        }
        break;
    }

    return (op->env_level > 0) ? 1 : 0;
}

/**
 * fm_operator_render — Render a single sample from one operator.
 *
 * @op:    Operator state (will be advanced).
 * @lfsr:  Pointer to noise LFSR state.
 *
 * Returns a 16-bit signed sample value (-32767 .. 32767), already
 * scaled by envelope and output level.
 */
static inline int16_t fm_operator_render(struct fm_operator *op,
                                          uint16_t *lfsr)
{
    int16_t sample;

    if (op->env_state == FM_ENV_IDLE)
        return 0;

    /* Look up waveform value at current phase */
    sample = fm_waveform_lookup(op->phase, op->waveform, lfsr);

    /* Scale by envelope level (0-255) */
    int32_t scaled = (int32_t)sample * (int32_t)op->env_level / 255;

    /* Scale by output level (0-255) */
    scaled = scaled * (int32_t)op->output_level / 255;

    /* Clamp to int16_t range */
    if (scaled > 32767) scaled = 32767;
    if (scaled < -32767) scaled = -32767;

    /* Advance phase */
    op->phase += op->phase_inc;

    return (int16_t)scaled;
}

/* ── Voice management ──────────────────────────────────────────────── */

/**
 * fm_find_voice — Find a voice by channel and note.
 *
 * @channel:  MIDI channel (0-15).
 * @note:     MIDI note number (0-127).
 *
 * Returns the voice index, or -1 if not found.
 */
static int fm_find_voice(uint8_t channel, uint8_t note)
{
    for (uint32_t i = 0; i < FM_SYNTH_MAX_VOICES; i++) {
        struct fm_voice *v = &g_fm_synth.voices[i];
        if (v->active && v->channel == channel && v->note == note)
            return (int)i;
    }
    return -1;
}

/**
 * fm_alloc_voice — Allocate a voice (steal oldest if all busy).
 *
 * @channel:  MIDI channel.
 * @note:     MIDI note number.
 * @velocity: Note velocity.
 *
 * Returns the voice index, or -1 on failure.
 */
static int fm_alloc_voice(uint8_t channel, uint8_t note, uint8_t velocity)
{
    /* Look for an inactive voice */
    for (uint32_t i = 0; i < FM_SYNTH_MAX_VOICES; i++) {
        if (!g_fm_synth.voices[i].active) {
            return (int)i;
        }
    }

    /* All voices busy — steal the first one (oldest / round-robin).
     * For a baseline, we just use voice 0 (simplest steal strategy).
     * A more sophisticated approach would track voice age. */
    /* Use a simple round-robin steal pointer */
    static uint32_t steal_next = 0;
    uint32_t idx = steal_next;
    steal_next = (steal_next + 1) % FM_SYNTH_MAX_VOICES;
    return (int)idx;
}

/**
 * fm_stop_voice — Transition a voice's operators to release phase.
 *
 * @idx:  Voice index.
 */
static void fm_stop_voice(uint32_t idx)
{
    if (idx >= FM_SYNTH_MAX_VOICES)
        return;
    struct fm_voice *v = &g_fm_synth.voices[idx];
    if (!v->active)
        return;

    /* Transition both operators to release phase */
    if (v->carrier.env_state != FM_ENV_IDLE) {
        v->carrier.env_state = FM_ENV_RELEASE;
        v->carrier.env_phase = 0;
    }
    if (v->modulator.env_state != FM_ENV_IDLE) {
        v->modulator.env_state = FM_ENV_RELEASE;
        v->modulator.env_phase = 0;
    }

    /* If release time is 0, immediately mark inactive */
    if (v->carrier.release_time == 0 && v->modulator.release_time == 0)
        v->active = 0;
}

/**
 * fm_reset_voice — Reset a voice to its default (idle) state.
 *
 * @idx:  Voice index.
 */
static void fm_reset_voice(uint32_t idx)
{
    if (idx >= FM_SYNTH_MAX_VOICES)
        return;
    struct fm_voice *v = &g_fm_synth.voices[idx];
    memset(v, 0, sizeof(*v));
}

/* ── Operator configuration helpers ────────────────────────────────── */

/**
 * fm_setup_voice — Configure a voice for a given note using GM instrument.
 *
 * Reads the current GM program for the voice's MIDI channel from
 * g_fm_synth.programs[] and applies its FM parameters (waveforms,
 * frequency ratios, output levels, modulation index, ADSR envelopes).
 *
 * @v:         Voice to configure.
 * @channel:   MIDI channel.
 * @note:      MIDI note number.
 * @velocity:  Note velocity (0-127).
 */
static void fm_setup_voice(struct fm_voice *v, uint8_t channel,
                            uint8_t note, uint8_t velocity)
{
    uint32_t sr = g_fm_synth.sample_rate;
    uint8_t pgm = g_fm_synth.programs[channel];
    if (pgm >= GM_PROGRAM_COUNT)
        pgm = 0;
    const struct fm_gm_instrument *inst = &g_fm_gm_instruments[pgm];

    /* Basic voice parameters */
    v->channel   = channel;
    v->note      = note;
    v->velocity  = velocity;
    v->active    = 1;

    /* Modulation index from instrument */
    v->mod_index = inst->mod_index;

    /* Compute frequency ratios */
    uint32_t note_inc = (note < 128) ? g_fm_phase_incs[note] : 0;

    /* ── Carrier operator ──────────────────────────────────────────── */
    memset(&v->carrier, 0, sizeof(v->carrier));

    v->carrier.phase     = 0;
    v->carrier.phase_inc = (note_inc * (uint32_t)inst->car_ratio + 1U) / 2U;
    v->carrier.waveform    = inst->car_wave;
    v->carrier.output_level = inst->car_level;

    /* Carrier ADSR from GM instrument */
    v->carrier.attack_time   = fm_rate_to_time(inst->car_attack, sr, 200);
    v->carrier.decay_time    = fm_rate_to_time(inst->car_decay,  sr, 400);
    v->carrier.sustain_level = inst->car_sustain;
    v->carrier.release_time  = fm_rate_to_time(inst->car_release, sr, 300);

    /* Speed up attack for high velocities */
    if (velocity > 100) {
        uint32_t t = (uint32_t)v->carrier.attack_time * 3U / 4U;
        if (t < 44) t = 44;
        v->carrier.attack_time = (uint16_t)t;
    } else if (velocity < 40) {
        uint32_t t = (uint32_t)v->carrier.attack_time * 4U / 3U;
        if (t > 65535) t = 65535;
        v->carrier.attack_time = (uint16_t)t;
    }

    /* ── Modulator operator ────────────────────────────────────────── */
    memset(&v->modulator, 0, sizeof(v->modulator));

    v->modulator.phase     = 0;
    v->modulator.phase_inc = (note_inc * (uint32_t)inst->mod_ratio + 1U) / 2U;
    v->modulator.waveform    = inst->mod_wave;
    v->modulator.output_level = inst->mod_level;

    /* Modulator ADSR from GM instrument */
    v->modulator.attack_time   = fm_rate_to_time(inst->mod_attack, sr, 200);
    v->modulator.decay_time    = fm_rate_to_time(inst->mod_decay,  sr, 400);
    v->modulator.sustain_level = inst->mod_sustain;
    v->modulator.release_time  = fm_rate_to_time(inst->mod_release, sr, 300);

    /* Start both operators in attack phase */
    v->carrier.env_state   = FM_ENV_ATTACK;
    v->carrier.env_phase   = 0;
    v->carrier.env_level   = 0;

    v->modulator.env_state = FM_ENV_ATTACK;
    v->modulator.env_phase = 0;
    v->modulator.env_level = 0;
}

/* ── Public API ─────────────────────────────────────────────────────── */

void fm_synth_init(uint32_t sample_rate)
{
    if (g_fm_synth.initialized)
        return;

    spinlock_init(&g_fm_lock);

    /* Validate / clamp sample rate */
    if (sample_rate < 8000)
        sample_rate = 8000;
    if (sample_rate > 192000)
        sample_rate = 192000;

    g_fm_synth.sample_rate    = sample_rate;
    g_fm_synth.master_volume  = 180;   /* ~71% default */
    g_fm_synth.noise_lfsr     = 0xACE1U;

    /* Clear all voices */
    memset(g_fm_synth.voices, 0, sizeof(g_fm_synth.voices));

    /* Reset all channels to GM program 0 (Acoustic Grand Piano) */
    memset(g_fm_synth.programs, 0, sizeof(g_fm_synth.programs));

    g_fm_synth.initialized = 1;

    kprintf("[OK] FM synth: initialised at %u Hz (%u voices)\n",
            sample_rate, FM_SYNTH_MAX_VOICES);
}

int fm_synth_note_on(uint8_t channel, uint8_t note, uint8_t velocity)
{
    int result = 0;

    if (!g_fm_synth.initialized)
        return -ENODEV;

    if (channel >= 16 || note > 127)
        return -EINVAL;

    /* Velocity 0 = note off */
    if (velocity == 0) {
        fm_synth_note_off(channel, note);
        return 0;
    }

    uint64_t irq_flags;
    spinlock_irqsave_acquire(&g_fm_lock, &irq_flags);

    /* If this note is already playing on this channel, restart it
     * (MIDI convention: new note-on stops the previous same-note). */
    int existing = fm_find_voice(channel, note);
    if (existing >= 0) {
        fm_stop_voice((uint32_t)existing);
    }

    /* Allocate a voice */
    int voice_idx = fm_alloc_voice(channel, note, velocity);
    if (voice_idx < 0) {
        spinlock_irqsave_release(&g_fm_lock, irq_flags);
        return -EAGAIN;
    }

    /* Configure the voice */
    fm_setup_voice(&g_fm_synth.voices[voice_idx], channel, note, velocity);

    spinlock_irqsave_release(&g_fm_lock, irq_flags);

    return result;
}

void fm_synth_note_off(uint8_t channel, uint8_t note)
{
    if (!g_fm_synth.initialized)
        return;
    if (channel >= 16 || note > 127)
        return;

    uint64_t irq_flags;
    spinlock_irqsave_acquire(&g_fm_lock, &irq_flags);

    int idx = fm_find_voice(channel, note);
    if (idx >= 0)
        fm_stop_voice((uint32_t)idx);

    spinlock_irqsave_release(&g_fm_lock, irq_flags);
}

void fm_synth_all_notes_off(void)
{
    if (!g_fm_synth.initialized)
        return;

    uint64_t irq_flags;
    spinlock_irqsave_acquire(&g_fm_lock, &irq_flags);

    for (uint32_t i = 0; i < FM_SYNTH_MAX_VOICES; i++) {
        struct fm_voice *v = &g_fm_synth.voices[i];
        if (v->active) {
            v->carrier.env_state = FM_ENV_IDLE;
            v->carrier.env_level = 0;
            v->modulator.env_state = FM_ENV_IDLE;
            v->modulator.env_level = 0;
            v->active = 0;
        }
    }

    spinlock_irqsave_release(&g_fm_lock, irq_flags);
}

uint32_t fm_synth_active_voice_count(void)
{
    uint32_t count = 0;

    for (uint32_t i = 0; i < FM_SYNTH_MAX_VOICES; i++) {
        if (g_fm_synth.voices[i].active)
            count++;
    }

    return count;
}

/**
 * fm_synth_program_change — Select a GM instrument for a MIDI channel.
 *
 * @channel:  MIDI channel (0-15).
 * @program:  GM program number (0-127).
 */
void fm_synth_program_change(uint8_t channel, uint8_t program)
{
    if (channel >= 16)
        return;

    if (program >= GM_PROGRAM_COUNT)
        program = 0;

    g_fm_synth.programs[channel] = program;
}

/**
 * fm_synth_get_program — Get the current GM program for a channel.
 *
 * @channel:  MIDI channel (0-15).
 * Returns the current GM program number (0-127), or 0 on invalid channel.
 */
uint8_t fm_synth_get_program(uint8_t channel)
{
    if (channel >= 16)
        return 0;

    return g_fm_synth.programs[channel];
}

/* ── Rendering ─────────────────────────────────────────────────────── */

/**
 * fm_render_voice — Render one sample from one voice.
 *
 * Implements 2-operator FM synthesis:
 *   output = sin(carrier_phase + mod_index * sin(modulator_phase))
 *          * envelope * velocity * master_volume
 *
 * The modulator output is scaled by the modulation index and added to
 * the carrier's phase, producing the characteristic FM sidebands.
 *
 * @v:      Voice to render.
 * @lfsr:   Pointer to noise LFSR state.
 *
 * Returns the rendered sample value (unscaled, before master volume),
 * or 0 if the voice is silent.
 */
static int32_t fm_render_voice(struct fm_voice *v, uint16_t *lfsr)
{
    /* Update envelopes */
    int car_alive = fm_env_update(&v->carrier);
    int mod_alive = fm_env_update(&v->modulator);

    if (!car_alive && !mod_alive) {
        /* Both operators finished — mark voice inactive */
        v->active = 0;
        return 0;
    }

    /* If carrier is done, voice is silent */
    if (!car_alive)
        return 0;

    /* Render modulator sample (it modulates the carrier's phase) */
    int16_t mod_sample = fm_operator_render(&v->modulator, lfsr);

    /* Modulate carrier phase: add modulator output * modulation index */
    int32_t mod_phase_offset = (int32_t)mod_sample
                               * (int32_t)v->mod_index / 128;

    /* Render carrier with modulated phase */
    int16_t car_sample = fm_operator_render(&v->carrier, lfsr);

    /* Apply velocity scaling (0-127) */
    int32_t out = (int32_t)car_sample * (int32_t)v->velocity / 127;

    return out;
}

void fm_synth_render(int16_t *buffer, uint32_t frames)
{
    if (!g_fm_synth.initialized || !buffer || frames == 0)
        return;

    /* Clear output buffer first */
    memset(buffer, 0, frames * 2 * sizeof(int16_t));

    /* Process each voice */
    for (uint32_t v = 0; v < FM_SYNTH_MAX_VOICES; v++) {
        struct fm_voice *voice = &g_fm_synth.voices[v];
        if (!voice->active)
            continue;

        /* Use a per-voice LFSR to avoid interference */
        uint16_t local_lfsr = g_fm_synth.noise_lfsr ^ (uint16_t)(v * 0x1234);

        /* Render each frame for this voice */
        for (uint32_t f = 0; f < frames; f++) {
            int32_t sample = fm_render_voice(voice, &local_lfsr);

            if (sample != 0) {
                /* Apply master volume */
                sample = sample * (int32_t)g_fm_synth.master_volume / 256;

                /* Hard-clamp to int16_t range */
                if (sample > 32767) sample = 32767;
                if (sample < -32767) sample = -32767;

                /* Mix into output buffer (stereo: same sample to L+R) */
                int16_t s16 = (int16_t)sample;
                int32_t l = (int32_t)buffer[f * 2]     + (int32_t)s16;
                int32_t r = (int32_t)buffer[f * 2 + 1] + (int32_t)s16;

                /* Clamp mixed output */
                if (l > 32767) l = 32767;
                if (l < -32767) l = -32767;
                if (r > 32767) r = 32767;
                if (r < -32767) r = -32767;

                buffer[f * 2]     = (int16_t)l;
                buffer[f * 2 + 1] = (int16_t)r;
            }
        }
    }
}

void fm_synth_render_mono(int16_t *buffer, uint32_t frames)
{
    if (!g_fm_synth.initialized || !buffer || frames == 0)
        return;

    memset(buffer, 0, frames * sizeof(int16_t));

    for (uint32_t v = 0; v < FM_SYNTH_MAX_VOICES; v++) {
        struct fm_voice *voice = &g_fm_synth.voices[v];
        if (!voice->active)
            continue;

        uint16_t local_lfsr = g_fm_synth.noise_lfsr ^ (uint16_t)(v * 0x5678);

        for (uint32_t f = 0; f < frames; f++) {
            int32_t sample = fm_render_voice(voice, &local_lfsr);

            if (sample != 0) {
                sample = sample * (int32_t)g_fm_synth.master_volume / 256;
                if (sample > 32767) sample = 32767;
                if (sample < -32767) sample = -32767;

                int32_t mixed = (int32_t)buffer[f] + (int32_t)sample;
                if (mixed > 32767) mixed = 32767;
                if (mixed < -32767) mixed = -32767;

                buffer[f] = (int16_t)mixed;
            }
        }
    }
}

/* ── Phase increment conversion ────────────────────────────────────── */

uint32_t fm_note_to_phase_inc(uint8_t note, uint32_t sample_rate)
{
    if (note > 127)
        return 0;

    if (sample_rate != FM_SYNTH_DEFAULT_RATE) {
        /* Recalculate for non-default sample rate */
        double freq = 440.0 * 1.059463094359;
        /* Actually just recompute — but for default rate use table */
    }

    return g_fm_phase_incs[note];
}

uint32_t fm_freq_to_phase_inc(uint32_t freq_fp, uint32_t sample_rate)
{
    /* freq_fp is in 24.8 fixed-point format */
    uint64_t freq_hz = (uint64_t)freq_fp;
    uint64_t inc = (freq_hz << 24U) / (uint64_t)sample_rate;
    return (uint32_t)inc;
}

/* ── Module initialisation ─────────────────────────────────────────── */

static int __init fm_synth_module_init(void)
{
    fm_synth_init(FM_SYNTH_DEFAULT_RATE);
    return 0;
}

module_init(fm_synth_module_init);

MODULE_LICENSE("MIT");
MODULE_VERSION("1.0.0");
MODULE_DESCRIPTION("FM synthesis engine for MIDI playback (2-operator OPL-like)");
MODULE_AUTHOR("1000 Changes Project");
