#!/bin/bash
# gen_config.sh — Generate kernel build config for /proc/config.gz
#
# Outputs a simple text representation of kernel build flags to stdout
# (or to the file specified as $1).
#
# This is used by the Makefile to produce build_config.txt, which is
# then gzip-compressed and embedded as /proc/config.gz.
#
# Usage: scripts/gen_config.sh [output_file]

OUTPUT="${1:-/dev/stdout}"

cat > "$OUTPUT" << 'CONFIG_EOF'
#
# Hermes OS — Kernel Build Configuration
# Auto-generated by scripts/gen_config.sh
#
# This file is compiled into the kernel image and is accessible
# via /proc/config.gz at runtime.
#

# ── General ──────────────────────────────────────────────────────
CONFIG_ARCH_X86_64=y
CONFIG_SMP=y
CONFIG_PREEMPT=y
CONFIG_SCHED_CFS=y
CONFIG_SCHED_DEADLINE=y
CONFIG_SCHED_RT=y
CONFIG_SCHED_IDLE=y
CONFIG_NUMA=y

# ── Memory Management ────────────────────────────────────────────
CONFIG_PMM_PAGE_POISON=y
CONFIG_VMM_DEMAND_PAGING=y
CONFIG_VMM_MPROTECT=y
CONFIG_VMM_HUGEPAGES=y
CONFIG_THP=y
CONFIG_KSM=y
CONFIG_ZRAM=y
CONFIG_ZSWAP=y
CONFIG_COMPACTION=y
CONFIG_OOM_KILLER=y
CONFIG_MEMFD=y
CONFIG_MSEAL=y
CONFIG_USERFAULTFD=y
CONFIG_MGLRU=y

# ── Filesystems ──────────────────────────────────────────────────
CONFIG_EXT2_FS=y
CONFIG_FAT32_FS=y
CONFIG_ISO9660_FS=y
CONFIG_TMPFS=y
CONFIG_PROCFS=y
CONFIG_DEVFS=y
CONFIG_SYSFS=y
CONFIG_DEBUGFS=y
CONFIG_OVERLAY_FS=y
CONFIG_FANOTIFY=y

# ── Networking ───────────────────────────────────────────────────
CONFIG_TCP=y
CONFIG_UDP=y
CONFIG_IPV6=y
CONFIG_BRIDGE=y
CONFIG_VLAN=y
CONFIG_ARP=y
CONFIG_SYN_COOKIES=y
CONFIG_NETFILTER=y
CONFIG_CONNTRACK=y
CONFIG_IPVS=y
CONFIG_WIREGUARD=y
CONFIG_TCP_CUBIC=y
CONFIG_TCP_BBR=y
CONFIG_NETLINK=y
CONFIG_AF_UNIX=y
CONFIG_AF_PACKET=y
CONFIG_CAN=y
CONFIG_VXLAN=y
CONFIG_GRE=y
CONFIG_VETH=y
CONFIG_TUN=y
CONFIG_IPIP=y

# ── Security ──────────────────────────────────────────────────────
CONFIG_SECCOMP=y
CONFIG_SECCOMP_FILTER=y
CONFIG_LANDLOCK=y
CONFIG_IMA=y
CONFIG_YAMA=y
CONFIG_KPTI=y
CONFIG_NX=y
CONFIG_SMAP=y
CONFIG_SMEP=y
CONFIG_UMIP=y
CONFIG_ASLR=y
CONFIG_EXECUTABLE_ONLY=y
CONFIG_STACK_GUARD=y

# ── Device Drivers ───────────────────────────────────────────────
CONFIG_E1000=y
CONFIG_AHCI=y
CONFIG_NVME=y
CONFIG_USB_EHCI=y
CONFIG_USB_MSC=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_BLK=y
CONFIG_ACPI=y
CONFIG_HPET=y
CONFIG_RTC=y
CONFIG_AC97=y
CONFIG_WATCHDOG=y
CONFIG_IPMI_KCS=y
CONFIG_TPM_TIS=y
CONFIG_DM_CORE=y
CONFIG_DM_LINEAR=y
CONFIG_DM_CRYPT=y
CONFIG_DM_ZERO=y
CONFIG_DM_ERROR=y
CONFIG_DM_VERITY=y
CONFIG_MD_RAID=y
CONFIG_LOOP=y
CONFIG_ZRAM=m
CONFIG_NETCONSOLE=y

# ── Debugging ────────────────────────────────────────────────────
CONFIG_LOCKDEP=y
CONFIG_NMI_WATCHDOG=y
CONFIG_KASAN=y
CONFIG_KMEMLEAK=y
CONFIG_KCOV=y
CONFIG_KPROBES=y
CONFIG_PSI=y
CONFIG_SYSCTL=y
CONFIG_DYNAMIC_DEBUG=y

CONFIG_EOF

exit 0
