/* cmd_help.c — help command */
#include "shell_cmds.h"
#include "printf.h"

void cmd_help(void) {
    kprintf("Available commands:\n");
    kprintf("  help     - Show this help\n");
    kprintf("  echo     - Print arguments\n");
    kprintf("  clear    - Clear screen\n");
    kprintf("  meminfo  - Show memory info\n");
    kprintf("  ps       - List processes\n");
    kprintf("  uptime   - Show uptime\n");
    kprintf("  reboot   - Reboot system\n");
    kprintf("  shutdown - Shutdown system (ACPI)\n");
    kprintf("  kill     - Kill process (kill <pid> [signal])\n");
    kprintf("  color    - Set color (color <fg> [bg])\n");
    kprintf("  hexdump  - Dump memory (hexdump <addr> [len])\n");
    kprintf("  date     - Show current date/time from RTC\n");
    kprintf("  cpuinfo  - Show CPU info\n");
    kprintf("  history  - Show command history\n");
    kprintf("  ls       - List files [dir]\n");
    kprintf("  cat      - Show file contents\n");
    kprintf("  write    - Write to file (write <name> <text>)\n");
    kprintf("  touch    - Create empty file\n");
    kprintf("  rm       - Remove file or empty dir\n");
    kprintf("  mkdir    - Create directory\n");
    kprintf("  stat     - Show file info\n");
    kprintf("  format   - Format filesystem\n");
    kprintf("  edit     - Text editor (edit <file>)\n");
    kprintf("  exec     - Execute ELF binary (exec <path>)\n");
    kprintf("  run      - Execute script file (run <path>)\n");
    kprintf("  ifconfig - Show network info\n");
    kprintf("  ping     - Ping host (ping [ip])\n");
    kprintf("  dns      - Resolve hostname (dns <host>)\n");
    kprintf("  curl     - HTTP GET (curl [-F] <url>)\n");
    kprintf("  udpsend  - Send UDP packet (udpsend <ip> <port> <data>)\n");
    kprintf("  beep     - PC speaker beep (beep [freq] [ms])\n");
    kprintf("  play     - Play note sequence (play <note> ...)\n");
    kprintf("  mouse    - Show mouse position and buttons\n");
    kprintf("  wc       - Count lines/words/bytes (wc <file>)\n");
    kprintf("  head     - Show first N lines (head <file> [n])\n");
    kprintf("  tail     - Show last N lines (tail <file> [n])\n");
    kprintf("  cp       - Copy file (cp <src> <dst>)\n");
    kprintf("  mv       - Move file (mv <src> <dst>)\n");
    kprintf("  grep     - Search text in file (grep <pattern> <file>)\n");
    kprintf("  df       - Show disk usage\n");
    kprintf("  free     - Show memory usage\n");
    kprintf("  whoami   - Show current process\n");
    kprintf("  hostname - Show hostname\n");
    kprintf("  env      - Show environment info\n");
    kprintf("  xxd      - Hex dump file (xxd <file>)\n");
    kprintf("  sleep    - Sleep N seconds (sleep <n>)\n");
    kprintf("  seq      - Print number sequence (seq [start] <end>)\n");
    kprintf("  arp      - Show ARP cache\n");
    kprintf("  route    - Show routing table\n");
    kprintf("  uname    - Show system info\n");
    kprintf("  lspci    - List PCI devices\n");
    kprintf("  dmesg    - Show boot log\n");
    kprintf("  cc       - Compile C source (cc <file> [out], cc --batch <list>)\n");
    kprintf("  sort     - Sort file lines (sort <file>)\n");
    kprintf("  find     - Find files (find <pattern>)\n");
    kprintf("  calc     - Calculator (calc <expr>)\n");
    kprintf("  uniq     - Remove duplicate lines (uniq <file>)\n");
    kprintf("  tr       - Translate chars (tr <from> <to> <file>)\n");
    kprintf("  tmux     - Terminal multiplexer (Ctrl-B prefix)\n");
    kprintf("  jobs     - List background processes\n");
    kprintf("  fg       - Bring background process to foreground (fg <pid>)\n");
    kprintf("  wait     - Wait for process to finish (wait <pid>)\n");
    kprintf("  tee      - Write stdin to file and stdout\n");
    kprintf("  cut      - Extract field from delimited file\n");
    kprintf("  paste    - Merge file lines\n");
    kprintf("  basename - Extract filename from path\n");
    kprintf("  dirname  - Extract directory from path\n");
    kprintf("  yes      - Repeatedly output a string\n");
    kprintf("  rev      - Reverse lines\n");
    kprintf("  nl       - Number lines\n");
    kprintf("  du       - Disk usage\n");
    kprintf("  id       - Print user identity\n");
    kprintf("  diff     - Compare two files\n");
    kprintf("  md5sum   - Hash a file\n");
    kprintf("  od       - Octal dump\n");
    kprintf("  expr     - Evaluate integer expression\n");
    kprintf("  test     - Evaluate condition\n");
    kprintf("  xargs    - Build args from pipe\n");
    kprintf("  printf   - Formatted output (printf <fmt> [args...])\n");
    kprintf("  time     - Time a command (time <cmd> [args...])\n");
    kprintf("  strings  - Print printable strings from file\n");
    kprintf("  tac      - Print file lines in reverse\n");
    kprintf("  base64   - Encode file as base64\n");
    kprintf("  cmos     - Show CMOS hardware configuration\n");
    kprintf("  hwinfo   - Comprehensive hardware summary\n");
    kprintf("  fbinfo   - Show display backend/framebuffer info\n");
    kprintf("  gui      - Launch GUI desktop environment\n");
    kprintf("  serial   - COM1 serial port (status/write)\n");
    kprintf("  lsusb    - List USB devices\n");
    kprintf("  lsblk    - List block devices (ATA/AHCI)\n");
    kprintf("  fat      - FAT32 filesystem (mount/ls/cat/stat)\n");
    kprintf("  chmod    - Change file permissions (chmod <mode> <path>)\n");
    kprintf("  chown    - Change file owner (chown <uid>[:<gid>] <path>)\n");
    kprintf("  login    - Log in as a user\n");
    kprintf("  logout   - Log out\n");
    kprintf("  users    - List all users\n");
    kprintf("  useradd  - Add a user\n");
    kprintf("  userdel  - Delete a user\n");
    kprintf("  passwd   - Change password\n");
    kprintf("  capprof  - Set process syscall profile (capprof <pid> <none|default|trusted>)\n");
    kprintf("\nShell features: Tab completion, history (up/down),\n");
    kprintf("  pipes (cmd1 | cmd2), redirection (cmd > file, cmd >> file)\n");
    kprintf("  background execution (cmd &)\n");
    kprintf("  variables: NAME=value, $NAME expansion\n");
}
