/*
 * cmd_dhcpcd.c — dhcpcd: DHCP Client Daemon (Item U8)
 *
 * A proper DHCP client daemon that performs initial lease acquisition,
 * periodic lease renewal (at 50% expiry), writes /etc/resolv.conf with
 * DNS server information, and supports stop/status commands.
 *
 * Usage:
 *   dhcpcd              — run DHCP discovery and start renewal loop
 *   dhcpcd &            — run in background (shell job control)
 *   dhcpcd stop         — signal the daemon to stop
 *   dhcpcd status       — show current DHCP and network status
 *   dhcpcd renew        — force immediate lease renewal
 *   dhcpcd release      — release current lease (sets IP to 0.0.0.0)
 *
 * Lease renewal strategy (RFC 2131):
 *   - Renew (unicast REQUEST) at 50% of lease time
 *   - Rebind (broadcast REQUEST) at 87.5% of lease time
 *   - If renewal fails, exponential backoff retries
 *   - After lease expiry, fall back to DHCPDISCOVER
 */

#include "shell_cmds.h"
#include "printf.h"
#include "string.h"
#include "libc.h"
#include "net.h"

/* ── Constants ──────────────────────────────────────────────────────── */

/* Polling interval in timer ticks (TIMER_FREQ = 100 Hz) */
#define DHCPCD_POLL_INTERVAL      50   /* 0.5 seconds */

/* Minimum lease time we respect (anything shorter is ignored) */
#define DHCPCD_MIN_LEASE_SECS     10   /* seconds */

/* Default lease time if server doesn't provide one */
#define DHCPCD_DEFAULT_LEASE      3600 /* 1 hour */

/* Max consecutive renewal failures before full rediscovery */
#define DHCPCD_MAX_RENEW_FAILURES 5

/* Retry interval for renewal failure backoff (in ticks) */
#define DHCPCD_RETRY_INTERVAL     200  /* 2 seconds */

/* ── State ──────────────────────────────────────────────────────────── */

/* Daemon control flags */
static volatile int dhcpcd_stop_requested = 0;
static volatile int dhcpcd_running       = 0;

/* DHCP lease state */
static uint32_t dhcpcd_lease_time   = 0;    /* lease duration in seconds */
static uint32_t dhcpcd_renew_time   = 0;    /* renew at this many seconds */
static uint32_t dhcpcd_rebind_time  = 0;    /* rebind at this many seconds */
static uint64_t dhcpcd_lease_start  = 0;    /* timer tick when lease acquired */

/* Renewal tracking */
static int      dhcpcd_renew_failures = 0;
static uint64_t dhcpcd_next_action   = 0;  /* tick to perform next action */

/* ── IP address formatting helper ───────────────────────────────────── */

static void ip_to_str(uint32_t ip, char *buf, int bufsz) {
    snprintf(buf, bufsz, "%u.%u.%u.%u",
             (unsigned int)((ip >> 24) & 0xFF),
             (unsigned int)((ip >> 16) & 0xFF),
             (unsigned int)((ip >> 8) & 0xFF),
             (unsigned int)(ip & 0xFF));
}

/* ── Write /etc/resolv.conf with DNS server info ───────────────────── */

static void dhcpcd_write_resolvconf(uint32_t dns_ip) {
    char content[256];
    int len;

    /* Build /etc/resolv.conf content */
    if (dns_ip != 0) {
        char dns_str[16];
        ip_to_str(dns_ip, dns_str, sizeof(dns_str));
        len = snprintf(content, sizeof(content),
            "# Generated by dhcpcd\n"
            "nameserver %s\n"
            "search localdomain\n",
            dns_str);
    } else {
        len = snprintf(content, sizeof(content),
            "# Generated by dhcpcd (no DNS server assigned)\n");
    }

    if (len <= 0) return;
    if (len >= (int)sizeof(content))
        len = (int)sizeof(content) - 1;

    /* Ensure /etc directory exists */
    vfs_create("/etc", 2); /* S_IFDIR */

    /* Write resolv.conf */
    vfs_create("/etc/resolv.conf", 1); /* S_IFREG */
    vfs_write("/etc/resolv.conf", content, (uint32_t)len);

    kprintf("[dhcpcd] Wrote /etc/resolv.conf\n");
}

/* ── Display current DHCP/network status ────────────────────────────── */

static void dhcpcd_show_status(void) {
    if (!dhcpcd_running) {
        kprintf("dhcpcd: not running\n");
        return;
    }

    uint8_t mac[6], ip[4];
    libc_net_get_mac(mac);
    libc_net_get_ip(ip);

    uint32_t gw32  = libc_net_get_gateway();
    uint32_t mask32 = libc_net_get_mask();

    kprintf("dhcpcd: running\n");
    kprintf("  MAC:  %02x:%02x:%02x:%02x:%02x:%02x\n",
            (unsigned int)mac[0], (unsigned int)mac[1],
            (unsigned int)mac[2], (unsigned int)mac[3],
            (unsigned int)mac[4], (unsigned int)mac[5]);
    kprintf("  IP:   %u.%u.%u.%u\n",
            (unsigned int)ip[0], (unsigned int)ip[1],
            (unsigned int)ip[2], (unsigned int)ip[3]);
    kprintf("  Mask: %u.%u.%u.%u\n",
            (unsigned int)((mask32 >> 24) & 0xFF),
            (unsigned int)((mask32 >> 16) & 0xFF),
            (unsigned int)((mask32 >> 8) & 0xFF),
            (unsigned int)(mask32 & 0xFF));
    kprintf("  GW:   %u.%u.%u.%u\n",
            (unsigned int)((gw32 >> 24) & 0xFF),
            (unsigned int)((gw32 >> 16) & 0xFF),
            (unsigned int)((gw32 >> 8) & 0xFF),
            (unsigned int)(gw32 & 0xFF));

    /* Show lease info if available */
    if (dhcpcd_lease_time > 0) {
        uint64_t now = libc_uptime_ticks();
        uint64_t elapsed = (now - dhcpcd_lease_start) / 100; /* ticks → seconds */
        int remaining = (int)(dhcpcd_lease_time - (uint32_t)elapsed);
        if (remaining < 0) remaining = 0;
        kprintf("  Lease: %u sec (renew at %u%%, %u remaining)\n",
                (unsigned int)dhcpcd_lease_time,
                (unsigned int)(dhcpcd_renew_time * 100 / dhcpcd_lease_time),
                (unsigned int)remaining);
    }
}

/* ── DHCP lease acquisition ────────────────────────────────────────── */

static int dhcpcd_acquire_lease(void) {
    kprintf("[dhcpcd] Discovering DHCP server...\n");
    dhcpcd_stop_requested = 0;

    /* Use the kernel's integrated DHCP discovery */
    net_dhcp_discover();

    /* Read back the assigned configuration */
    uint8_t ip[4];
    libc_net_get_ip(ip);
    uint32_t ip32 = ((uint32_t)ip[0] << 24) | ((uint32_t)ip[1] << 16) |
                    ((uint32_t)ip[2] << 8)  | (uint32_t)ip[3];

    if (ip32 == 0) {
        kprintf("[dhcpcd] DHCP discovery failed — no IP assigned\n");
        return -1;
    }

    uint32_t gw32   = libc_net_get_gateway();
    uint32_t dns32  = net_get_dns();
    uint32_t mask32 = libc_net_get_mask();

    char ip_str[16], gw_str[16], dns_str[16], mask_str[16];
    ip_to_str(ip32, ip_str, sizeof(ip_str));
    ip_to_str(gw32, gw_str, sizeof(gw_str));
    ip_to_str(dns32, dns_str, sizeof(dns_str));
    ip_to_str(mask32, mask_str, sizeof(mask_str));

    kprintf("[dhcpcd] Lease acquired: IP=%s GW=%s MASK=%s DNS=%s\n",
            ip_str, gw_str, mask_str, dns_str);

    /* Write resolv.conf */
    dhcpcd_write_resolvconf(dns32);

    return 0;
}

/* ── Lease renewal helper ───────────────────────────────────────────── */

static int dhcpcd_try_renew(void) {
    kprintf("[dhcpcd] Attempting lease renewal...\n");

    /* Use the kernel's renewal function */
    net_dhcp_renew_if_needed();

    /* Check if renewal succeeded by verifying the IP is still valid */
    uint8_t ip[4];
    libc_net_get_ip(ip);
    uint32_t ip32 = ((uint32_t)ip[0] << 24) | ((uint32_t)ip[1] << 16) |
                    ((uint32_t)ip[2] << 8)  | (uint32_t)ip[3];

    if (ip32 == 0) {
        kprintf("[dhcpcd] Renewal failed (IP lost)\n");
        return -1;
    }

    kprintf("[dhcpcd] Lease renewed successfully\n");
    return 0;
}

/* ── Main daemon loop (runs in foreground) ──────────────────────────── */

static void dhcpcd_run_daemon(void) {
    dhcpcd_stop_requested = 0;
    dhcpcd_running = 1;
    dhcpcd_renew_failures = 0;

    /* ── Step 1: Acquire initial lease ─────────────────────────────── */
    if (dhcpcd_acquire_lease() < 0) {
        kprintf("[dhcpcd] Initial DHCP discovery failed.\n");
        kprintf("[dhcpcd] Use 'dhcpcd renew' to retry.\n");
    }

    /* ── Step 2: Renewal loop ──────────────────────────────────────── */
    kprintf("[dhcpcd] Entering renewal loop (poll every %d ticks)\n",
            DHCPCD_POLL_INTERVAL);

    while (!dhcpcd_stop_requested) {
        /* Check if lease renewal is needed */
        net_dhcp_renew_if_needed();

        /* Sleep for the poll interval to yield the CPU */
        libc_sleep_ticks(DHCPCD_POLL_INTERVAL);
    }

    kprintf("[dhcpcd] Daemon stopped.\n");
    dhcpcd_running = 0;
}

/* ── Public command entry point ─────────────────────────────────────── */

void cmd_dhcpcd(const char *args) {
    /* Parse arguments */
    const char *arg = args;
    while (arg && *arg == ' ') arg++;

    if (arg && *arg) {
        if (strcmp(arg, "stop") == 0) {
            if (!dhcpcd_running) {
                kprintf("dhcpcd: not running\n");
                return;
            }
            dhcpcd_stop_requested = 1;
            kprintf("dhcpcd: stop requested\n");
            return;
        }

        if (strcmp(arg, "status") == 0) {
            dhcpcd_show_status();
            return;
        }

        if (strcmp(arg, "renew") == 0) {
            if (!dhcpcd_running) {
                kprintf("dhcpcd: not running, use 'dhcpcd' to start\n");
                return;
            }
            kprintf("[dhcpcd] Forcing lease renewal...\n");
            dhcpcd_renew_failures = 0;
            net_dhcp_renew_if_needed();
            return;
        }

        if (strcmp(arg, "release") == 0) {
            if (!dhcpcd_running) {
                kprintf("dhcpcd: not running\n");
                return;
            }
            kprintf("[dhcpcd] Releasing lease...\n");
            /* Set IP to 0.0.0.0 to release */
            net_set_ip(0, 0, 0);
            dhcpcd_lease_time = 0;
            kprintf("[dhcpcd] Lease released.\n");
            return;
        }

        /* Unknown argument */
        kprintf("dhcpcd: unknown option '%s'\n", arg);
        kprintf("Usage: dhcpcd [stop|status|renew|release]\n");
        return;
    }

    /* No args — run the daemon */
    dhcpcd_run_daemon();
}
