/* cmd_shar.c — create shell archive (encode files as shell script) */
#include "shell_cmds.h"
#include "libc.h"
#include "printf.h"
#include "string.h"

static void shar_base64(uint8_t *data, uint32_t len) {
    static const char *b64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    int out = 0;
    for (uint32_t i = 0; i < len; i += 3) {
        uint32_t val = data[i] << 16;
        if (i+1 < len) val |= data[i+1] << 8;
        if (i+2 < len) val |= data[i+2];
        kprintf("%c", b64[(val >> 18) & 0x3F]);
        kprintf("%c", b64[(val >> 12) & 0x3F]);
        if (i+1 < len) kprintf("%c", b64[(val >> 6) & 0x3F]);
        else kprintf("=");
        if (i+2 < len) kprintf("%c", b64[val & 0x3F]);
        else kprintf("=");
        out++;
        if (out >= 76/4) { kprintf("\n"); out = 0; }
    }
    if (out) kprintf("\n");
}

void cmd_shar(const char *args) {
    if (!args || !args[0]) {
        kprintf("Usage: shar <file> [file2 ...]\n");
        return;
    }

    kprintf("#!/bin/sh\n");
    kprintf("# This is a shell archive (shar)\n");
    kprintf("# Generated by shar utility\n");

    char path[64];
    const char *p = args;
    while (*p) {
        int i = 0;
        while (*p && *p != ' ' && i < 63) path[i++] = *p++;
        path[i] = '\0';
        while (*p == ' ') p++;

        /* Strip leading slash for extraction */
        const char *fname = path;
        if (fname[0] == '/') fname++;

        kprintf("echo 'x - %s'\n", fname);
        kprintf("if test -f '%s'; then rm '%s'; fi\n", fname, fname);

        static uint8_t buf[4096];
        uint32_t size = 0;
        if (vfs_read(path, buf, sizeof(buf), &size) != 0) {
            kprintf("# ERROR: cannot read '%s'\n", path);
            continue;
        }
        kprintf("base64_decode() {\n");
        kprintf("  %s\n", "sed 's/./&/g' | ...");
        kprintf("}\n");
        kprintf("cat > '%s' << 'SHAR_EOF'\n", fname);
        shar_base64(buf, size);
        kprintf("SHAR_EOF\n");
        kprintf("echo 'wrote %s (%u bytes)'\n", fname, (unsigned int)size);
    }
}
