#ifndef SIGNAL_H
#define SIGNAL_H

/**
 * @file signal.h
 *
 * Signal definitions for the OS kernel.
 *
 * This header defines all supported signal numbers (1-63), signal info
 * structures, sigaction flags, and alternate signal stack types.
 *
 * Signal numbering follows POSIX convention:
 *   - Signals 1-31 are standard signals (each has a well-defined meaning)
 *   - Signals 32-63 are real-time signals (SIGRTMIN..SIGRTMAX)
 *
 * Standard signal actions (unless overridden by sigaction):
 *   Term   — Default action is to terminate the process
 *   Core   — Terminate and dump core
 *   Ign    — Default action is to ignore the signal
 *   Stop   — Default action is to stop (suspend) the process
 *   Cont   — Default action is to continue if stopped
 *
 * All signals except SIGKILL (9) and SIGSTOP (19) can be caught or ignored
 * by the process via signal_register() / sigaction().
 */

#include "types.h"

/* ── si_code origins for siginfo_t.si_code ────────────────────────────── */
#define SI_USER     0   /* signal sent by kill(2), raise(3), or abort(3) */
#define SI_KERNEL   1   /* signal sent by the kernel (e.g., SIGSEGV, SIGFPE) */
#define SI_QUEUE    2   /* signal sent by sigqueue(3) (includes siginfo) */
#define SI_TKILL    3   /* signal sent by tkill(2) / tgkill(2) */

/* ── si_code values for SIGSEGV ───────────────────────────────────────── */
#define SEGV_MAPERR 1   /* address not mapped into address space */
#define SEGV_ACCERR 2   /* invalid permissions for mapped object */

/* ── si_code values for SIGBUS ────────────────────────────────────────── */
/* non-existent physical address (e.g., mmap beyond end of file) */
#define BUS_ADRERR   3

/**
 * Signal info structure (subset of POSIX siginfo_t).
 *
 * Delivered to user-space via siginfo (when SA_SIGINFO is set) and
 * used internally by the kernel for signal routing.
 */
struct siginfo {
    int      si_signo;    /* signal number */
    int      si_errno;    /* errno (unused) */
    int      si_code;     /* signal code — identifies origin / subtype */
    uint32_t si_pid;      /* sending process PID */
    uint32_t si_uid;      /* real user ID of sender */
    void    *si_addr;     /* fault address (for SIGSEGV/SIGBUS only) */
    int      si_status;   /* exit value or termination signal (for SIGCHLD) */
};

/* ══════════════════════════════════════════════════════════════════════════
 *  Standard Signals (1-31)
 * ══════════════════════════════════════════════════════════════════════════
 *
 * Each standard signal has a conventional meaning.  Unless noted, all signals
 * are delivered to the process synchronously or asynchronously from the
 * kernel, another process, or the terminal.
 */

/* SIGHUP  — Hangup (Term).
 * Sent when the controlling terminal is disconnected or the controlling
 * process exits.  Daemons typically reload configuration on this signal. */
#define SIGHUP    1

/* SIGINT  — Interrupt from keyboard (Term).
 * Generated when the user presses Ctrl-C.  Can be caught for clean
 * shutdown. */
#define SIGINT    2

/* SIGQUIT — Quit from keyboard (Core).
 * Generated when the user presses Ctrl-\ (Ctrl-Backslash).  Causes the
 * process to terminate with a core dump if not caught. */
#define SIGQUIT   3

/* SIGILL  — Illegal instruction (Core).
 * The CPU attempted to execute an invalid or privileged instruction.
 * Also raised on certain machine-check exceptions. */
#define SIGILL    4

/* SIGTRAP — Trace/breakpoint trap (Core).
 * Used by debuggers (ptrace, gdb) for breakpoints and single-stepping.
 * Also used internally by the kernel for kprobes and uprobes. */
#define SIGTRAP   5

/* SIGABRT — Abort (Core).
 * Generated by abort(3); the process terminates and dumps core.
 * Also used internally by assert(3) on assertion failure. */
#define SIGABRT   6

/* SIGBUS  — Bus error (Core).
 * Access to an invalid address that is not a page-mapping violation
 * (e.g., misaligned access, mmap beyond file end).  See BUS_ADRERR etc. */
#define SIGBUS    7

/* SIGFPE  — Floating-point exception (Core).
 * Arithmetic error: division by zero, overflow, underflow, or invalid
 * operation.  Named for historical reasons — also covers integer
 * divide-by-zero. */
#define SIGFPE    8

/* SIGKILL — Kill (Term, cannot be caught or ignored).
 * Immediately terminates the process.  Always delivered, regardless of
 * signal mask.  Used by SIGKILL-initiated shutdown. */
#define SIGKILL   9

/* SIGUSR1 — User-defined signal 1 (Term).
 * Application-defined meaning.  Unused by the kernel. */
#define SIGUSR1   10

/* SIGSEGV — Segmentation fault (Core).
 * Invalid memory access — dereferencing a bad pointer, writing to
 * read-only memory, executing from non-executable memory. */
#define SIGSEGV   11

/* SIGUSR2 — User-defined signal 2 (Term).
 * Application-defined meaning.  Unused by the kernel. */
#define SIGUSR2   12

/* SIGPIPE — Broken pipe (Term).
 * Written to a pipe, socket, or FIFO with no reader on the other end.
 * Shell pipelines commonly catch this to avoid noisy error messages. */
#define SIGPIPE   13

/* SIGALRM — Alarm clock (Term).
 * Timer expiration from alarm(2) or setitimer(2) with ITIMER_REAL.
 * The default handler terminates the process. */
#define SIGALRM   14

/* SIGTERM — Termination (Term).
 * Generic signal requesting process termination.  Unlike SIGKILL it can
 * be caught, allowing the process to perform cleanup. */
#define SIGTERM   15

/* SIGSTKFLT — Stack fault (Term, Linux-specific).
 * Coprocessor stack fault on older x86 systems.  Modern systems do not
 * generate this signal; reserved for compatibility. */
#define SIGSTKFLT 16

/* SIGCHLD — Child status changed (Ign).
 * Sent to the parent when a child process terminates, stops, or resumes.
 * The parent can inspect status via wait(2) / waitpid(2). */
#define SIGCHLD   17

/* SIGCONT — Continue (Cont).
 * Resumes execution of a stopped process.  Ignored if the process is
 * not stopped.  Can be caught, but the default action (continue) is
 * usually what is wanted. */
#define SIGCONT   18

/* SIGSTOP — Stop (Stop, cannot be caught or ignored).
 * Suspends the process immediately.  SIGCONT resumes execution.
 * Used by job-control shells (Ctrl-Z) and the kernel. */
#define SIGSTOP   19

/* SIGTSTP — Keyboard stop (Stop).
 * Generated when the user presses Ctrl-Z.  Similar to SIGSTOP but can
 * be caught, allowing the process to save state before stopping. */
#define SIGTSTP   20

/* SIGTTIN — Background read from controlling terminal (Stop).
 * Delivered when a background process group attempts to read from the
 * controlling terminal.  The process is stopped until foreground. */
#define SIGTTIN   21

/* SIGTTOU — Background write to controlling terminal (Stop).
 * Delivered when a background process group attempts to write to the
 * controlling terminal (unless TOSTOP is disabled). */
#define SIGTTOU   22

/* SIGURG  — Urgent data on socket (Ign).
 * Out-of-band (urgent) data received on a socket.  Used by TCP with
 * the MSG_OOB flag.  Most applications ignore this signal. */
#define SIGURG    23

/* SIGXCPU — CPU time limit exceeded (Core).
 * The process has exceeded its soft CPU time resource limit
 * (RLIMIT_CPU).  If caught, the process gets one last chance before
 * SIGKILL after the hard limit. */
#define SIGXCPU   24

/* SIGXFSZ — File size limit exceeded (Core).
 * The process attempted to extend a file beyond RLIMIT_FSIZE.
 * Writes that would exceed the limit return EFBIG. */
#define SIGXFSZ   25

/* SIGVTALRM — Virtual alarm clock (Term).
 * Timer expiration from setitimer(2) with ITIMER_VIRTUAL — counts
 * only CPU time spent in user mode. */
#define SIGVTALRM 26

/* SIGPROF — Profiling alarm clock (Term).
 * Timer expiration from setitimer(2) with ITIMER_PROF — counts CPU
 * time in both user and kernel modes.  Used by profilers (gprof). */
#define SIGPROF   27

/* SIGWINCH — Window resize (Ign).
 * The terminal window size has changed.  Applications like editors
 * and terminal emulators catch this to redraw the display. */
#define SIGWINCH  28

/* SIGIO   — I/O now possible (Ign).
 * An asynchronous I/O event occurred (F_SETFL with O_ASYNC, or
 * aio_read/aio_write completion). */
#define SIGIO     29

/* SIGPWR  — Power failure (Term, size 30).
 * System power failure imminent.  Uninterruptible power supply (UPS)
 * daemons catch this to initiate clean shutdown.
 * NOTE: signal 30 is deliberately unused in many ports; 31 is SIGSYS. */
/* (signal 30 reserved — not defined in this port) */

/* SIGSYS  — Bad system call (Core).
 * The process invoked an invalid syscall number.  Also raised by
 * seccomp when a syscall is denied. */
#define SIGSYS    31

/* ══════════════════════════════════════════════════════════════════════════
 *  Real-Time Signals (32-63)
 * ══════════════════════════════════════════════════════════════════════════
 *
 * Realtime signals (SIGRTMIN=32 .. SIGRTMAX=63) have no predefined
 * meaning.  They are queued in order of delivery and support an
 * associated data value (via sigqueue).  Multiple pending instances of
 * the same realtime signal are queued separately (unlike standard signals
 * which are coalesced).  Applications define their own semantics.
 */
#define SIGRTMIN  32
#define SIGRTMAX  63

/* SIGCHLD si_code values */
#define CLD_EXITED    1
#define CLD_KILLED    2
#define CLD_DUMPED    3
#define CLD_TRAPPED   4
#define CLD_STOPPED   5
#define CLD_CONTINUED 6

typedef void (*signal_handler_t)(int signum);

#define SIG_MAX  64  /* signals 1-63 (bit 63 is max addressable in uint64_t mask) */
#define SIG_DFL  ((signal_handler_t)0)  /* Default action */
#define SIG_IGN  ((signal_handler_t)1)  /* Ignore */

/* Alternate signal stack (sigaltstack) */
typedef struct {
    void   *ss_sp;       /* stack base/pointer */
    int     ss_flags;    /* SS_DISABLE, SS_ONSTACK */
    size_t  ss_size;     /* stack size */
} stack_t;

#define SS_DISABLE     2
#define SS_ONSTACK     1
#define SS_AUTODISARM  (1U << 31)  /* Linux 4.7+: automatic disarm on signal delivery */

/* Minimum alternate signal stack size — must be at least this when enabling */
#define MINSIGSTKSZ  2048
/* Default/suggested alternate signal stack size */
#define SIGSTKSZ     8192

/* sigaction flags — POSIX SA_* flags */
#define SA_NOCLDSTOP  0x00000001
#define SA_NOCLDWAIT  0x00000002
#define SA_SIGINFO    0x00000004
#define SA_ONSTACK    0x08000000
#define SA_RESTART    0x10000000
#define SA_NODEFER    0x40000000
#define SA_RESETHAND  0x80000000

/* Mask of all currently recognised SA_* flags.
 * Any bit set outside this mask in sa_flags shall be rejected with EINVAL. */
#define SA_VALID_FLAGS  (SA_NOCLDSTOP | SA_NOCLDWAIT | SA_SIGINFO \
                         | SA_ONSTACK | SA_RESTART | SA_NODEFER | SA_RESETHAND)

/* Send signal to process by pid; 0 = success, -1 = not found */
int signal_send(uint32_t pid, int signum);
int signal_send_group(uint32_t pgid, int signum);
int signal_send_pgid(uint32_t pgid, int signum);

/* Extended signal send with siginfo.
 * @from_userspace: 1 if siginfo was provided by userspace (via rt_sigqueueinfo,
 *                  pidfd_send_signal), 0 if generated by kernel code.
 *                  Controls whether siginfo is subjected to userspace-origin
 *                  validation rules (reject SI_USER, clamp unknown codes). */
int signal_send_info(uint32_t pid, int signum, struct siginfo *info,
                     int from_userspace);

/* Check if any pending (non-masked) signal has SA_RESTART flag set.
 * Used by blocking syscalls to decide whether to restart the syscall
 * instead of returning -EINTR when interrupted by a signal. */
int signal_has_sa_restart(void);

/* Check if any pending (non-masked) signal exists for the current process.
 * Used by blocking syscall handlers to decide whether to return -ERESTARTSYS. */
int signal_has_pending_unmasked(void);

/* ── Convert kernel-internal ERESTART* codes to what userspace should see ──
 *
 * Called from syscall_dispatch_internal() after a syscall handler returns.
 * If the return value is one of the ERESTART* codes, this function:
 *   1. If SA_RESTART applies → returns the same value so the caller
 *      can re-dispatch the syscall
 *   2. Otherwise → returns -EINTR
 * For non-ERESTART* values it returns them unchanged.
 */
int64_t signal_convert_erestartsys(int64_t retval);

/* Check and deliver any pending signals for the current process.
 * Called by scheduler before returning to a READY process. */
void signal_check(void);

/* Register a signal handler for the current process */
void signal_register(int signum, signal_handler_t handler);
void signal_register_flags(int signum, signal_handler_t handler, uint32_t flags);

/* Mask/unmask signals for the current process (1-bit per signal number) */
void signal_mask(uint64_t sigmask);
void signal_unmask(uint64_t sigmask);

/* Retrieve siginfo for a pending signal (returns NULL if none stored).
 * Caller should clear the info after use. */
struct process;
struct siginfo *signal_get_info(struct process *p, int signum);

/* Deliver SIGCHLD with full siginfo_t to parent.  Called when a process
 * transitions to ZOMBIE state.  Must NOT hold the child's sig_lock.
 * @si_code: CLD_EXITED, CLD_KILLED, or CLD_DUMPED
 * @si_status: exit code (CLD_EXITED) or termination signal (CLD_KILLED/CLD_DUMPED) */
void signal_notify_parent(struct process *p, int si_code, int si_status);

/* Deliver a signal to the currently running user-space process by building
 * a signal frame on the user stack and redirecting the saved execution context.
 * Called from signal_check() in interrupt context when a user handler exists.
 * Returns 0 on success, -errno on failure. */
struct interrupt_frame;
int signal_setup_frame_userspace(struct interrupt_frame *frame, int signum,
                                 uint64_t handler_addr,
                                 struct siginfo *info,
                                 uint64_t saved_sigmask);

#endif
